import { bank } from "./_builder";

// Day 1 — Agent Fundamentals (25 questions)
// Concept names must match lib/curriculum.ts CONCEPTS.
export const day1 = bank("day-1", "Agent Fundamentals", [
  {
    c: "LLM vs Agent", cat: "conceptual", t: "conceptual", d: "easy",
    q: "What most fundamentally distinguishes an agent from a single LLM call?",
    o: [
      "An agent uses a larger model",
      "An agent loops: it can take actions, observe results, and decide again toward a goal",
      "An agent always produces JSON",
      "An agent never hallucinates",
    ],
    a: 1,
    e: "A single LLM call maps input to output once. An agent wraps a model in a loop that can act, observe, and re-decide toward a goal. Model size and output format are unrelated.",
  },
  {
    c: "LLM vs Agent", cat: "conceptual", t: "conceptual", d: "easy",
    q: "A service classifies each incoming email as spam or not with one model call and returns the label. Is this an agent?",
    o: [
      "Yes, because it uses an LLM",
      "Yes, because it makes a decision",
      "No, it is a single-shot classification with no action/observation loop",
      "No, because classification is impossible for LLMs",
    ],
    a: 2,
    e: "Using an LLM does not make something an agent. This is one-shot classification with no loop, no tools, and no observation of results — not an agent.",
  },
  {
    c: "LLM vs Agent", cat: "application", t: "scenario", d: "medium",
    q: "You need to translate a fixed block of text once and return it. Which design is most appropriate?",
    o: [
      "A multi-agent system with a translator and a reviewer agent",
      "A single LLM call",
      "An agent loop with a translation tool and retries",
      "A RAG pipeline over a translation memory",
    ],
    a: 1,
    e: "A one-shot task with no need for tools, iteration, or external data is best served by a single LLM call. Everything else adds cost and failure surface for no benefit.",
  },
  {
    c: "Agent loop", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Which sequence best describes one iteration of the agent loop?",
    o: [
      "Reason → act → observe → reason again",
      "Retrieve → embed → chunk → answer",
      "Validate → execute → log → stop",
      "Prompt → fine-tune → deploy",
    ],
    a: 0,
    e: "The agent loop is: the model reasons, chooses an action/tool, the environment returns an observation, and the model reasons again. The other options describe RAG, validation, and training.",
  },
  {
    c: "Agent loop", cat: "application", t: "scenario", d: "medium",
    q: "In an agent loop, the model decides that no tool is needed and answers directly. Is this valid?",
    o: [
      "No, every loop iteration must call a tool",
      "No, the loop must terminate with an error",
      "Yes, deciding to answer directly is a legitimate action",
      "Yes, but only if a tool was called earlier",
    ],
    a: 2,
    e: "Choosing to answer directly (rather than call a tool) is a valid action in the loop. Requiring a tool call every iteration is a common misconception.",
  },
  {
    c: "Agent loop", cat: "debugging", t: "debugging", d: "medium",
    q: "An agent keeps calling the same tool with the same arguments and never finishes. What is the most likely root cause?",
    o: [
      "The model is too small",
      "No termination condition or the observation isn't changing the model's decision",
      "The tool schema has too many fields",
      "Embeddings are stale",
    ],
    a: 1,
    e: "Repeating the same call forever indicates the loop lacks a termination guard and/or the observation isn't influencing the next decision. Model size and embeddings are irrelevant here.",
  },
  {
    c: "Agent loop", cat: "debugging", t: "debugging", d: "hard",
    q: "An agent produces a correct final answer but takes 12 tool calls where 2 would do. Which fix targets the cause without removing capability?",
    o: [
      "Remove all tools",
      "Improve the reasoning/instructions so the model plans before acting, and cap iterations",
      "Switch to a single LLM call with no tools",
      "Add three more tools",
    ],
    a: 1,
    e: "Excessive tool calls usually reflect poor planning. Better instructions plus an iteration cap reduce waste while keeping capability. Removing all tools or capping to a single call may break the task; adding tools worsens selection.",
  },
  {
    c: "Tools & environment", cat: "conceptual", t: "conceptual", d: "easy",
    q: "In agent terminology, what is a 'tool'?",
    o: [
      "The prompt template",
      "An external capability (e.g. a function or API) the agent can invoke",
      "The model's training data",
      "The temperature setting",
    ],
    a: 1,
    e: "A tool is an external capability the agent can call to affect or read the environment. Prompts, training data, and sampling settings are not tools.",
  },
  {
    c: "Tools & environment", cat: "conceptual", t: "conceptual", d: "medium",
    q: "What is the 'environment' in an agent system?",
    o: [
      "The IDE the developer uses",
      "The system/world the agent reads from and acts upon via tools and observations",
      "The GPU the model runs on",
      "The list of few-shot examples",
    ],
    a: 1,
    e: "The environment is whatever the agent perceives and affects — files, APIs, a database, the web. It is not the developer's tooling or hardware.",
  },
  {
    c: "Tools & environment", cat: "application", t: "scenario", d: "medium",
    q: "An agent has 40 tools and frequently picks the wrong one. What is the most direct improvement?",
    o: [
      "Add more tools so it has more choices",
      "Reduce and sharpen the tool set, with clear, distinct descriptions",
      "Increase temperature",
      "Remove the agent loop",
    ],
    a: 1,
    e: "Too many overlapping tools degrade selection. Curating a smaller set with distinct, clear descriptions improves the model's ability to choose correctly.",
  },
  {
    c: "Tools & environment", cat: "architecture", t: "architecture", d: "hard",
    q: "You are designing an agent that can send emails and delete files. What is the most important environment-level design choice?",
    o: [
      "Use the largest model available",
      "Bound the environment: scope permissions and require confirmation for irreversible actions",
      "Add more few-shot examples",
      "Cache tool outputs",
    ],
    a: 1,
    e: "When tools can cause irreversible external effects, the priority is bounding the environment: least-privilege permissions and confirmation gates. Model size, examples, and caching don't address the safety boundary.",
  },
  {
    c: "When not to use agents", cat: "application", t: "scenario", d: "easy",
    q: "A task is fully specified and solvable by a deterministic function (e.g. compute a checksum). What should you use?",
    o: [
      "An agent with a checksum tool",
      "A multi-agent debate",
      "The deterministic function directly",
      "A RAG pipeline",
    ],
    a: 2,
    e: "If a deterministic function solves it, call the function. Wrapping it in an agent adds latency, cost, and failure modes for zero benefit.",
  },
  {
    c: "When not to use agents", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Which statement best reflects mature judgment about agents?",
    o: [
      "Agentic architecture is always superior to simpler designs",
      "Agents are a design choice justified by need, not a default",
      "Every LLM feature should be an agent",
      "Agents remove the need for validation",
    ],
    a: 1,
    e: "Agents are one design choice among many. They should be used when iteration, tools, and adaptivity are genuinely needed — not by default.",
  },
  {
    c: "When not to use agents", cat: "application", t: "scenario", d: "medium",
    q: "A workflow always runs the same three steps in the same order with no branching. Best design?",
    o: [
      "A fixed sequential workflow (possibly with LLM steps), not an autonomous agent",
      "An autonomous agent that decides the steps each run",
      "A multi-agent committee",
      "A single embedding lookup",
    ],
    a: 0,
    e: "Deterministic, fixed-order work is a workflow. An autonomous agent that re-plans each run adds nondeterminism and cost without benefit when the steps never change.",
  },
  {
    c: "When not to use agents", cat: "architecture", t: "architecture", d: "hard",
    q: "You must choose between a workflow and an agent for a task with unpredictable steps that depend on intermediate results. Which is the deciding factor for choosing an agent?",
    o: [
      "The task needs a database",
      "The path cannot be fixed in advance and benefits from the model adapting based on observations",
      "You want to use function calling",
      "The output must be JSON",
    ],
    a: 1,
    e: "Agents earn their complexity when the control flow can't be predetermined and must adapt to observations. Needing a DB, JSON, or function calling doesn't by itself require an agent.",
  },
  {
    c: "Agent failure modes", cat: "debugging", t: "failure-mode", d: "easy",
    q: "Which of these is a classic agent failure mode?",
    o: [
      "Answering in complete sentences",
      "An infinite loop with no termination guard",
      "Using a system prompt",
      "Returning a number",
    ],
    a: 1,
    e: "Infinite loops from missing termination are a hallmark agent failure. The others are normal behavior.",
  },
  {
    c: "Agent failure modes", cat: "debugging", t: "debugging", d: "medium",
    q: "An agent 'calls' a tool named `getWeatherPro` that you never defined. What is this called and where do you fix it?",
    o: [
      "A hallucinated tool; reject unknown tool names at the dispatch boundary",
      "A schema error; enlarge the schema",
      "A retrieval failure; re-chunk documents",
      "A termination failure; add retries",
    ],
    a: 0,
    e: "Inventing a nonexistent tool is a hallucinated action. The fix is to validate/reject unknown tool names where the agent's requests are dispatched.",
  },
  {
    c: "Agent failure modes", cat: "debugging", t: "failure-mode", d: "medium",
    q: "An agent picks a valid tool but the wrong one for the step (e.g. currency-convert instead of unit-convert). This is best described as:",
    o: [
      "A termination failure",
      "A tool-selection failure",
      "A malformed-JSON failure",
      "A chunking failure",
    ],
    a: 1,
    e: "Choosing a real but inappropriate tool is a tool-selection failure, usually improved with clearer tool descriptions and instructions.",
  },
  {
    c: "Agent failure modes", cat: "architecture", t: "architecture", d: "hard",
    q: "To make an agent robust to a tool timing out, what is the best design?",
    o: [
      "Let the exception crash the run so you notice",
      "Return the timeout to the loop as an observation the model can react to (e.g. retry or choose another path)",
      "Ignore the tool result silently",
      "Remove the tool permanently",
    ],
    a: 1,
    e: "Robust agents treat tool errors as observations, letting the loop adapt (retry, fall back, or report). Crashing, ignoring, or removing the tool are all worse.",
  },
  {
    c: "LLM vs Agent", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Which of the following does an LLM by itself NOT do?",
    o: [
      "Predict likely next tokens",
      "Autonomously take real-world actions without an orchestration layer",
      "Follow instructions in a prompt",
      "Produce text output",
    ],
    a: 1,
    e: "A bare LLM generates text; it cannot take real-world actions on its own. Acting requires an orchestration/tool layer — i.e. an agent.",
  },
  {
    c: "Agent loop", cat: "application", t: "application", d: "medium",
    q: "You want to observe exactly what your agent is doing each step for debugging. What should you log?",
    o: [
      "Only the final answer",
      "The reasoning/decision, the chosen action, and the resulting observation each iteration",
      "Only the model name",
      "Only token counts",
    ],
    a: 1,
    e: "To debug a loop you need per-iteration visibility: the decision, the action taken, and the observation returned. The final answer alone hides the loop's behavior.",
  },
  {
    c: "Tools & environment", cat: "conceptual", t: "conceptual", d: "easy",
    q: "An 'observation' in an agent loop is:",
    o: [
      "The user's original goal",
      "The result returned after the agent takes an action",
      "The model's weights",
      "The temperature",
    ],
    a: 1,
    e: "An observation is what the environment returns after an action, which the model then reasons over. The goal is the input; weights and temperature are model internals/settings.",
  },
  {
    c: "When not to use agents", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Which is a symptom that you over-engineered a task into an agent?",
    o: [
      "The task runs faster than a single call",
      "The 'agent' always executes the identical fixed steps but now with added latency and nondeterminism",
      "The agent uses fewer tokens",
      "The output is more deterministic",
    ],
    a: 1,
    e: "If the agent always does the same fixed thing yet adds latency and nondeterminism, a plain function or workflow was the right tool — a sign of over-engineering.",
  },
  {
    c: "Agent failure modes", cat: "debugging", t: "debugging", d: "hard",
    q: "An agent gives different final answers on identical inputs across runs, sometimes wrong. Which change most directly increases reliability for a step that should be exact?",
    o: [
      "Raise temperature for more creativity",
      "Move the exact part to a deterministic tool/function and have the agent call it",
      "Add more agents to vote",
      "Increase max iterations",
    ],
    a: 1,
    e: "For parts that must be exact, delegate them to a deterministic tool rather than trusting probabilistic generation. Voting and more iterations don't guarantee correctness; higher temperature worsens it.",
  },
  {
    c: "Agent loop", cat: "architecture", t: "architecture", d: "hard",
    q: "Which pairing correctly maps concept to role in the loop?",
    o: [
      "Model = external capability; Tool = reasoning engine",
      "Model = reasoning engine; Tool = external capability; Observation = result of an action",
      "Observation = the goal; State = the temperature",
      "Environment = the prompt; Action = the model weights",
    ],
    a: 1,
    e: "The model is the reasoning engine, a tool is an external capability, and an observation is the result of an action. The other mappings are scrambled.",
  },
]);
