import { bank } from "./_builder";

// Day 2 — Tools & Function Calling (25 questions)
export const day2 = bank("day-2", "Tools & Function Calling", [
  {
    c: "Function calling", cat: "conceptual", t: "conceptual", d: "easy",
    q: "When a model 'calls a function', what actually happens?",
    o: [
      "The model executes the function code itself",
      "The model emits a structured request naming a tool and arguments; your code executes it",
      "The function is added to the model's weights",
      "The function's source is embedded and retrieved",
    ],
    a: 1,
    e: "The model does not run code. It emits a structured tool request (name + arguments). Your application executes the tool and returns the result. This boundary is where validation belongs.",
  },
  {
    c: "Function calling", cat: "application", t: "scenario", d: "medium",
    q: "After the model requests `getPrice({ticker:'AAPL'})`, what is the correct next step in the loop?",
    o: [
      "Return the raw request to the user",
      "Execute the tool, then feed its result back to the model as an observation",
      "Fine-tune the model on the result",
      "Immediately end the run",
    ],
    a: 1,
    e: "You execute the requested tool and return its result to the model so it can continue reasoning. The tool request itself isn't the answer.",
  },
  {
    c: "Tool schemas", cat: "conceptual", t: "conceptual", d: "easy",
    q: "What is the primary purpose of a tool schema?",
    o: [
      "To speed up the GPU",
      "To describe the tool's name, parameters, and types so the model can form correct calls",
      "To store the model's memory",
      "To encrypt tool outputs",
    ],
    a: 1,
    e: "A schema tells the model how to call the tool correctly — its name, parameters, and types. Clear schemas reduce malformed calls.",
  },
  {
    c: "Tool schemas", cat: "application", t: "scenario", d: "medium",
    q: "A model frequently passes a date as '03/04/25' when your tool needs ISO 'YYYY-MM-DD'. Best first fix?",
    o: [
      "Increase temperature",
      "Make the schema explicit about the required format and give an example in the description",
      "Add a second date tool",
      "Switch to a bigger model only",
    ],
    a: 1,
    e: "Ambiguous parameter descriptions cause malformed arguments. Specifying the exact format (and an example) in the schema is the most direct fix.",
  },
  {
    c: "Tool schemas", cat: "architecture", t: "architecture", d: "hard",
    q: "You have two tools: `search(query)` and `searchNews(query, sinceDate)`. The model keeps confusing them. Which schema-level change helps most?",
    o: [
      "Give each a distinct, non-overlapping description stating exactly when to use it",
      "Rename both to `search`",
      "Remove all parameters",
      "Merge them but keep both descriptions identical",
    ],
    a: 0,
    e: "Confusion between similar tools is a description/selection problem. Distinct descriptions that state precisely when each applies improve selection. Identical names/descriptions make it worse.",
  },
  {
    c: "Argument validation", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Why validate a model's tool arguments before executing?",
    o: [
      "Because the model may produce out-of-range or wrong-typed values",
      "Because validation makes the model faster",
      "Because it changes the model's weights",
      "Validation is unnecessary if you have a schema",
    ],
    a: 0,
    e: "Models can emit arguments that are wrong-typed or out of range even when schema-shaped. Validating before execution prevents bad input from reaching tool logic.",
  },
  {
    c: "Argument validation", cat: "debugging", t: "debugging", d: "medium",
    q: "Your `transfer(amount)` tool crashed on `amount: -500`. The schema only said `amount: number`. What's the fix?",
    o: [
      "Catch the crash and retry the same call",
      "Add business validation (e.g. amount > 0) before executing, and return a structured error otherwise",
      "Remove the schema",
      "Increase max iterations",
    ],
    a: 1,
    e: "`-500` is schema-valid (a number) but business-invalid. Add a value check before execution and return a structured error the loop can react to. Blind retries repeat the bad call.",
  },
  {
    c: "Argument validation", cat: "application", t: "scenario", d: "medium",
    q: "When argument validation fails, what is the best behavior in an agent loop?",
    o: [
      "Throw and crash the run",
      "Silently substitute a default and continue",
      "Return a structured error observation so the model can correct and retry",
      "Skip the tool and answer anyway",
    ],
    a: 2,
    e: "Returning a structured error lets the model see what was wrong and fix its arguments. Crashing or silently defaulting hides the problem; skipping may produce a wrong answer.",
  },
  {
    c: "Tool error handling", cat: "conceptual", t: "conceptual", d: "easy",
    q: "In a robust agent, a tool timeout should be treated as:",
    o: [
      "A fatal crash",
      "An observation the loop can react to",
      "A reason to increase temperature",
      "A schema change",
    ],
    a: 1,
    e: "Robust agents treat tool errors, including timeouts, as observations so the loop can retry, fall back, or report — rather than crashing.",
  },
  {
    c: "Tool error handling", cat: "debugging", t: "debugging", d: "medium",
    q: "A tool intermittently returns an error 20% of the time due to a flaky API. Which handling is most appropriate?",
    o: [
      "Bounded retries with backoff, then a graceful fallback/report if still failing",
      "Infinite retries until it succeeds",
      "Ignore errors and use the last successful value forever",
      "Delete the tool",
    ],
    a: 0,
    e: "Bounded retries with backoff handle transient failures without risking an infinite loop; a graceful fallback covers persistent failure. Infinite retries and stale values are unsafe.",
  },
  {
    c: "Tool error handling", cat: "architecture", t: "architecture", d: "hard",
    q: "An agent orchestrates 5 tools; occasionally one is unavailable. What design keeps the overall task resilient?",
    o: [
      "Make every tool mandatory so failures are obvious",
      "Return tool availability/errors as observations and let the agent choose alternative paths or degrade gracefully",
      "Run all tools in parallel and ignore failures",
      "Cache one tool's output and reuse it for all tools",
    ],
    a: 1,
    e: "Surfacing errors/availability as observations lets the agent adapt (alternate tool, degraded answer). Hard-requiring every tool makes the system brittle; ignoring failures corrupts results.",
  },
  {
    c: "Tool selection", cat: "conceptual", t: "conceptual", d: "easy",
    q: "'Tool selection' refers to:",
    o: [
      "Choosing which tool (or none) is appropriate for the current step",
      "Selecting the model temperature",
      "Picking an embedding model",
      "Choosing a vector database",
    ],
    a: 0,
    e: "Tool selection is the model's decision of which tool — or none — to use for the current step.",
  },
  {
    c: "Tool selection", cat: "application", t: "scenario", d: "medium",
    q: "A user asks 'What is 15% of 240?' and the agent has a calculator tool. Ideal behavior?",
    o: [
      "Answer from memory without the tool for guaranteed correctness",
      "Call the calculator tool to compute exactly",
      "Refuse because math is unsafe",
      "Call a web-search tool",
    ],
    a: 1,
    e: "Exact arithmetic should be delegated to the deterministic calculator tool rather than trusting probabilistic generation. Web search is the wrong tool here.",
  },
  {
    c: "Tool selection", cat: "debugging", t: "debugging", d: "hard",
    q: "An agent has `sqlQuery` and `vectorSearch`. For a precise lookup by ID it keeps using `vectorSearch` and returns fuzzy matches. Best fix?",
    o: [
      "Delete `sqlQuery`",
      "Clarify in each tool's description when to use exact structured lookups vs semantic search, and give an example",
      "Increase top-k on vector search",
      "Raise temperature",
    ],
    a: 1,
    e: "Using semantic search for an exact lookup is a selection error. Descriptions must clearly delineate when exact structured queries beat semantic search. Tuning top-k or temperature doesn't fix selection.",
  },
  {
    c: "Function calling", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Which statement about function calling is TRUE?",
    o: [
      "The model guarantees semantically correct arguments",
      "The model proposes calls; your code is responsible for validating and executing them",
      "Function calling eliminates the need for error handling",
      "The model can call functions not provided to it safely",
    ],
    a: 1,
    e: "Function calling is a proposal mechanism; your code validates and executes. It guarantees neither correct arguments nor eliminates error handling, and unknown tools should be rejected.",
  },
  {
    c: "Tool schemas", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Which is a 'schema mismatch' failure?",
    o: [
      "The tool returns a value the model uses correctly",
      "The model calls the tool with a parameter name/type the tool doesn't accept",
      "The model answers without a tool",
      "The tool runs slower than expected",
    ],
    a: 1,
    e: "A schema mismatch is when the call's parameters (names/types) don't match what the tool accepts. Latency and not-calling are different issues.",
  },
  {
    c: "Argument validation", cat: "application", t: "application", d: "medium",
    q: "You want bad arguments to never reach a tool's body. Where do you put validation?",
    o: [
      "Inside the tool body after the risky operation",
      "At the dispatch boundary, before invoking the tool body",
      "In the model's system prompt only",
      "In the final answer formatting",
    ],
    a: 1,
    e: "Validation belongs at the dispatch boundary, before the tool body runs, so invalid arguments are rejected before any side effect. Prompts help but cannot guarantee it.",
  },
  {
    c: "Tool error handling", cat: "debugging", t: "failure-mode", d: "easy",
    q: "Which is NOT a tool failure mode?",
    o: [
      "Timeout",
      "Unavailable tool",
      "Wrong output shape",
      "The model using correct grammar",
    ],
    a: 3,
    e: "Timeouts, unavailability, and wrong output shapes are tool failure modes. Correct grammar is not a failure.",
  },
  {
    c: "Tool selection", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Adding many overlapping tools tends to:",
    o: [
      "Always improve accuracy",
      "Degrade tool-selection accuracy due to ambiguity",
      "Reduce latency",
      "Guarantee correct arguments",
    ],
    a: 1,
    e: "Overlapping tools create ambiguity that degrades selection. Curated, distinct tools help the model choose correctly.",
  },
  {
    c: "Function calling", cat: "debugging", t: "debugging", d: "hard",
    q: "The model returns valid JSON for a tool call, the tool runs, but the final answer ignores the tool's result. Where is the bug most likely?",
    o: [
      "The tool schema",
      "The loop isn't feeding the tool result back to the model before it answers",
      "The embedding model",
      "The temperature",
    ],
    a: 1,
    e: "If the answer ignores the tool result, the orchestration likely isn't returning the observation to the model before it produces the final answer. The schema and embeddings are unrelated.",
  },
  {
    c: "Tool schemas", cat: "application", t: "application", d: "easy",
    q: "A good tool description should primarily tell the model:",
    o: [
      "How the tool is implemented internally",
      "What the tool does and when to use it, plus parameter meanings",
      "The server's IP address",
      "The developer's name",
    ],
    a: 1,
    e: "Descriptions should convey what the tool does, when to use it, and what each parameter means. Implementation details and infra are irrelevant to selection.",
  },
  {
    c: "Argument validation", cat: "debugging", t: "failure-mode", d: "hard",
    q: "A `setWeight(sector, value)` call arrives with `value: 1.4` (meant to be a fraction ≤ 1). The schema says `number`. What best prevents downstream corruption?",
    o: [
      "Round it to 1.0 silently",
      "Reject with a business-rule error (value must be in [0,1]) and return it as an observation",
      "Accept it; the schema passed",
      "Retry the exact call",
    ],
    a: 1,
    e: "1.4 is schema-valid but violates the business rule (fractions in [0,1]). Reject with a clear error observation so the model can correct. Silent rounding hides the mistake; accepting corrupts state.",
  },
  {
    c: "Tool selection", cat: "architecture", t: "architecture", d: "medium",
    q: "To help an agent reliably choose 'no tool' when it can answer directly, you should:",
    o: [
      "Force a tool call every turn",
      "Make 'answer directly' an explicit, well-described option and instruct when it's appropriate",
      "Remove the ability to answer directly",
      "Add more tools",
    ],
    a: 1,
    e: "Reliable 'no tool' behavior comes from making direct answering an explicit option with guidance on when to use it. Forcing tool calls or removing the option undermines correctness.",
  },
  {
    c: "Tool error handling", cat: "application", t: "scenario", d: "medium",
    q: "A tool returns `{ok:false, error:'rate limited'}`. What should the agent ideally do next?",
    o: [
      "Crash",
      "Wait/backoff and retry within a bounded limit, or choose an alternative",
      "Report success to the user",
      "Immediately delete the tool",
    ],
    a: 1,
    e: "A rate-limit error calls for bounded backoff/retry or an alternative path. Crashing or falsely reporting success are wrong.",
  },
  {
    c: "Function calling", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Which best describes the relationship between the model and tool execution?",
    o: [
      "Model decides; application executes",
      "Application decides; model executes",
      "Both decide and execute simultaneously",
      "Neither decides; the schema executes",
    ],
    a: 0,
    e: "The model decides which tool to call with what arguments; the application executes it. This separation is central to safe function calling.",
  },
]);
