import { bank } from "./_builder";

// Day 3 — RAG (25 questions)
export const day3 = bank("day-3", "Retrieval-Augmented Generation", [
  {
    c: "Why RAG exists", cat: "conceptual", t: "conceptual", d: "easy",
    q: "What problem does RAG primarily solve?",
    o: [
      "It makes the model smaller",
      "It grounds generation in specific, current, or private knowledge the model doesn't have in its weights",
      "It removes the need for prompts",
      "It fine-tunes the model automatically",
    ],
    a: 1,
    e: "RAG injects external context (current/private/specific) at query time so the model can answer from data outside its training. It doesn't shrink or retrain the model.",
    ref: "Lewis et al., 2020 (arXiv:2005.11401)",
  },
  {
    c: "Why RAG exists", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Which statement about RAG is correct?",
    o: [
      "RAG changes the model's weights with your documents",
      "RAG supplies context in the prompt; it does not modify the model",
      "RAG eliminates hallucination entirely",
      "RAG requires fine-tuning first",
    ],
    a: 1,
    e: "RAG augments the prompt with retrieved context; it does not alter weights (that's fine-tuning). It reduces but does not eliminate hallucination.",
  },
  {
    c: "Why RAG exists", cat: "application", t: "scenario", d: "medium",
    q: "You need a chatbot to answer from a company handbook updated weekly. Best approach?",
    o: [
      "Fine-tune a new model every week",
      "Use RAG over the handbook so updates are reflected immediately",
      "Rely on the base model's general knowledge",
      "Paste the entire handbook into every prompt regardless of size",
    ],
    a: 1,
    e: "Frequently changing, specific knowledge is ideal for RAG: update the corpus and retrieval reflects it, no retraining. Fine-tuning weekly is costly; the base model won't know it; pasting everything wastes context and may exceed limits.",
  },
  {
    c: "Embeddings", cat: "conceptual", t: "conceptual", d: "easy",
    q: "What is an embedding?",
    o: [
      "A compressed image",
      "A vector representation placing semantically similar text near each other",
      "A database index type",
      "A type of prompt",
    ],
    a: 1,
    e: "Embeddings map text to vectors so that semantically similar text is close in vector space, enabling similarity search.",
    ref: "OpenAI embeddings guide",
  },
  {
    c: "Embeddings", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Two chunks have high cosine similarity to a query. What does that guarantee?",
    o: [
      "They contain the exact answer",
      "They are about semantically similar topics — not necessarily that they contain the needed fact",
      "They are the newest documents",
      "They are grammatically correct",
    ],
    a: 1,
    e: "High similarity means 'about similar things', not 'contains the answer'. This distinction is the core RAG debugging trap.",
  },
  {
    c: "Embeddings", cat: "application", t: "application", d: "medium",
    q: "You retrieve with embeddings but exact product codes (e.g. 'X-4471') are missed. What complements embeddings here?",
    o: [
      "Higher temperature",
      "Keyword/exact (lexical) matching or hybrid search alongside semantic search",
      "A larger LLM",
      "More few-shot examples",
    ],
    a: 1,
    e: "Embeddings capture meaning, not exact tokens, so precise codes are often missed. Hybrid (lexical + semantic) retrieval recovers exact-match cases.",
  },
  {
    c: "Chunking", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Why do we chunk documents for RAG?",
    o: [
      "To make files smaller on disk",
      "To create retrievable units precise enough to match queries yet meaningful enough to answer them",
      "To encrypt them",
      "To translate them",
    ],
    a: 1,
    e: "Chunking splits documents into units that are precise enough to retrieve and large enough to be useful. It's about retrieval quality, not storage.",
  },
  {
    c: "Chunking", cat: "debugging", t: "debugging", d: "medium",
    q: "Answers are missing information that spans two adjacent paragraphs. Which chunking change likely helps?",
    o: [
      "Use much smaller chunks with no overlap",
      "Add chunk overlap so ideas spanning boundaries aren't split",
      "Remove chunking entirely",
      "Increase temperature",
    ],
    a: 1,
    e: "Information split across a chunk boundary is lost. Overlapping chunks preserve cross-boundary context. Smaller no-overlap chunks worsen it.",
  },
  {
    c: "Chunking", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Which is a common chunking failure?",
    o: [
      "Chunks that respect sentence/section boundaries",
      "Chunks so large they dilute relevance, or so small they lose context",
      "Chunks with helpful metadata",
      "Chunks with overlap",
    ],
    a: 1,
    e: "Both extremes hurt: oversized chunks dilute relevance; undersized chunks lose the surrounding context needed to answer.",
  },
  {
    c: "Retrieval relevance", cat: "debugging", t: "debugging", d: "hard",
    q: "An agent retrieves three chunks highly similar to the question, but none contain the answer, so it hallucinates. Which component should you investigate FIRST?",
    o: [
      "The generation temperature",
      "Retrieval/relevance: whether the needed information is chunked, embedded, and retrievable at all",
      "The system prompt's tone",
      "The output formatter",
    ],
    a: 1,
    e: "Similar-but-irrelevant results point at retrieval: is the answering content even in the corpus, chunked well, and reachable by top-k? Fixing generation can't supply missing context.",
  },
  {
    c: "Retrieval relevance", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Semantically similar retrieval results can still be irrelevant because:",
    o: [
      "Similarity measures topical closeness, not whether the fact needed is present",
      "Cosine similarity is always wrong",
      "Embeddings are random",
      "The model ignores context",
    ],
    a: 0,
    e: "Similarity ranks by topical/semantic closeness, which does not ensure the specific needed fact is in those chunks.",
  },
  {
    c: "Retrieval relevance", cat: "application", t: "scenario", d: "medium",
    q: "top-k=3 returns near-duplicates of the same passage, missing a second relevant source. What helps?",
    o: [
      "Lower k to 1",
      "Increase k and/or add de-duplication/diversity (e.g. MMR) so distinct relevant sources appear",
      "Raise temperature",
      "Remove metadata",
    ],
    a: 1,
    e: "Near-duplicate crowding is addressed by increasing k and promoting diversity (e.g. maximal marginal relevance) so distinct sources surface. Lowering k makes it worse.",
  },
  {
    c: "Grounding & hallucination", cat: "conceptual", t: "conceptual", d: "easy",
    q: "'Grounding' in RAG means:",
    o: [
      "Running the model on local hardware",
      "Constraining the answer to be supported by retrieved context",
      "Lowering the temperature to zero",
      "Storing embeddings on disk",
    ],
    a: 1,
    e: "Grounding means basing the answer on retrieved evidence rather than free generation, reducing hallucination.",
  },
  {
    c: "Grounding & hallucination", cat: "application", t: "scenario", d: "medium",
    q: "To reduce hallucination when retrieval finds nothing relevant, the system should:",
    o: [
      "Answer confidently from the model's general knowledge",
      "Say it cannot find the information rather than fabricating an answer",
      "Increase k until something returns",
      "Lower similarity thresholds to force results",
    ],
    a: 1,
    e: "When no relevant context exists, the grounded behavior is to admit it rather than fabricate. Forcing low-quality results in only invites hallucination.",
  },
  {
    c: "Grounding & hallucination", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Which is a RAG failure where the pipeline 'looks' fine but answers are wrong?",
    o: [
      "The answering document simply isn't in the corpus",
      "The vector store is online",
      "Chunks have metadata",
      "Embeddings were computed",
    ],
    a: 0,
    e: "If the answering document isn't ingested, retrieval can only return similar-but-wrong chunks — a silent, common failure. The others are healthy signals.",
  },
  {
    c: "Why RAG exists", cat: "architecture", t: "architecture", d: "hard",
    q: "For the future Research Agent, why is RAG preferable to stuffing all reports into one prompt?",
    o: [
      "Prompts can't contain text",
      "Retrieval selects only relevant context, controlling cost and staying within context limits while improving focus",
      "RAG guarantees correctness",
      "Stuffing is always cheaper",
    ],
    a: 1,
    e: "RAG retrieves only relevant chunks, keeping prompts focused and within limits and controlling cost — important at scale. It doesn't guarantee correctness.",
  },
  {
    c: "Embeddings", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Cosine similarity between two embeddings measures:",
    o: [
      "The angle/closeness between the vectors as a proxy for semantic similarity",
      "The file sizes",
      "The number of tokens",
      "The publication date",
    ],
    a: 0,
    e: "Cosine similarity compares vector direction as a proxy for semantic closeness. It's unrelated to file size, token count, or date.",
  },
  {
    c: "Chunking", cat: "application", t: "application", d: "medium",
    q: "Adding source + section metadata to chunks primarily enables:",
    o: [
      "Faster GPUs",
      "Metadata filtering and citations (e.g. restrict retrieval to a document or show provenance)",
      "Smaller embeddings",
      "Automatic fine-tuning",
    ],
    a: 1,
    e: "Metadata enables filtering (e.g. by source/section) and provenance/citations, improving precision and trust.",
  },
  {
    c: "Retrieval relevance", cat: "debugging", t: "debugging", d: "hard",
    q: "Retrieval quality is good in tests but poor in production where users paraphrase heavily. Most likely cause?",
    o: [
      "The LLM got smaller",
      "Query/document embedding mismatch — user phrasing differs from stored chunks; consider query rewriting or better embeddings",
      "The disk is full",
      "Temperature is too low",
    ],
    a: 1,
    e: "Heavy paraphrase creates a gap between query and chunk embeddings. Query rewriting/expansion or stronger embedding models close it. Disk and temperature are unrelated.",
  },
  {
    c: "Grounding & hallucination", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Even with perfect retrieval, a RAG system can still hallucinate if:",
    o: [
      "The model ignores the provided context and answers from priors",
      "The chunks are too relevant",
      "Metadata is present",
      "Embeddings are normalized",
    ],
    a: 0,
    e: "If the model doesn't actually ground its answer in the retrieved context (ignoring it for its priors), hallucination persists despite good retrieval.",
  },
  {
    c: "Why RAG exists", cat: "conceptual", t: "conceptual", d: "easy",
    q: "RAG stands for:",
    o: [
      "Random Answer Generation",
      "Retrieval-Augmented Generation",
      "Recursive Agent Graph",
      "Ranked Aggregate Grounding",
    ],
    a: 1,
    e: "RAG = Retrieval-Augmented Generation. (This is memorization; the harder questions test whether you can reason about retrieval.)",
  },
  {
    c: "Chunking", cat: "architecture", t: "architecture", d: "hard",
    q: "You must retrieve precisely from long legal contracts with cross-references. Which chunking strategy is most defensible?",
    o: [
      "One chunk per whole contract",
      "Structure-aware chunks (by clause/section) with overlap and section metadata",
      "Fixed 5-character chunks",
      "No chunking; embed the title only",
    ],
    a: 1,
    e: "Structure-aware chunking by clause/section, with overlap and metadata, preserves meaning and supports precise, cited retrieval in cross-referenced documents. The extremes fail.",
  },
  {
    c: "Retrieval relevance", cat: "conceptual", t: "conceptual", d: "easy",
    q: "'top-k' in retrieval refers to:",
    o: [
      "The k most similar chunks returned for a query",
      "The temperature setting",
      "The number of tools",
      "The k largest documents",
    ],
    a: 0,
    e: "top-k returns the k highest-similarity chunks for the query. It is a retrieval parameter, not a model setting.",
  },
  {
    c: "Grounding & hallucination", cat: "application", t: "scenario", d: "medium",
    q: "To make a RAG answer auditable, you should:",
    o: [
      "Hide which chunks were used",
      "Return citations to the retrieved chunks/sources used",
      "Increase temperature",
      "Remove all metadata",
    ],
    a: 1,
    e: "Citing the retrieved sources makes answers auditable and lets users verify grounding — directly aligned with 'answer to reality'.",
  },
  {
    c: "Embeddings", cat: "debugging", t: "failure-mode", d: "medium",
    q: "You embedded documents with one model and queries with a different, incompatible model. Likely result?",
    o: [
      "Better retrieval",
      "Degraded retrieval because the vectors live in different spaces",
      "No effect",
      "Faster search",
    ],
    a: 1,
    e: "Query and document embeddings must come from compatible models/spaces; mixing incompatible models misaligns the vector space and degrades retrieval.",
  },
]);
