import { bank } from "./_builder";

// Day 4 — Structured Outputs (25 questions)
export const day4 = bank("day-4", "Structured Outputs", [
  {
    c: "Structured output", cat: "conceptual", t: "conceptual", d: "easy",
    q: "What is 'structured output' from an LLM?",
    o: [
      "Output in complete sentences",
      "Output constrained to a machine-readable shape (e.g. JSON matching a schema)",
      "Output in a different language",
      "Output with citations",
    ],
    a: 1,
    e: "Structured output constrains generation to a declared machine-readable shape so downstream code can rely on it.",
  },
  {
    c: "Structured output", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Why is structured output the 'bridge' to deterministic systems?",
    o: [
      "It makes the model deterministic",
      "It converts fuzzy language into typed data that code can validate and act on",
      "It removes the need for validation",
      "It guarantees semantic correctness",
    ],
    a: 1,
    e: "Structured output turns language into typed data downstream systems can process — but it guarantees shape, not correctness, and still needs validation.",
  },
  {
    c: "Schema validation", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Schema validation checks that output has:",
    o: [
      "Correct meaning",
      "The right fields, types, and allowed enum values",
      "The newest information",
      "A friendly tone",
    ],
    a: 1,
    e: "Schema validation checks shape: required fields, types, and enum membership. It says nothing about whether values are meaningful.",
  },
  {
    c: "Business-rule validation", cat: "conceptual", t: "conceptual", d: "medium",
    q: "The output `{ \"maxSectorWeight\": -5 }` passes a schema requiring a number. What does this illustrate?",
    o: [
      "Schema-valid does not imply business-valid",
      "The schema is broken",
      "Negative numbers are always invalid in JSON",
      "The model cannot output numbers",
    ],
    a: 0,
    e: "A negative weight is a valid number (schema-valid) but semantically illegal (business-invalid). This is the central Day 4 insight.",
  },
  {
    c: "Business-rule validation", cat: "application", t: "scenario", d: "medium",
    q: "Which check belongs in business validation, not schema validation?",
    o: [
      "`value` is a number",
      "`value` is between 0 and 1",
      "`type` field is present",
      "`sector` is a string",
    ],
    a: 1,
    e: "Range checks like 0 ≤ value ≤ 1 encode business meaning. Presence, type, and field existence are schema-level checks.",
  },
  {
    c: "Business-rule validation", cat: "debugging", t: "debugging", d: "hard",
    q: "Two constraints each pass schema and business validation individually: `Technology >= 0.40` and `Technology <= 0.25`. What must ALSO be validated?",
    o: [
      "The JSON indentation",
      "Cross-constraint consistency (no contradictory pair)",
      "The field ordering",
      "The string encoding",
    ],
    a: 1,
    e: "Individually valid constraints can still contradict each other. Cross-constraint (consistency/feasibility) validation is required to catch min>max style conflicts.",
  },
  {
    c: "Malformed output handling", cat: "conceptual", t: "conceptual", d: "easy",
    q: "'Malformed output' most directly refers to:",
    o: [
      "Output that is impolite",
      "Output that is invalid JSON or missing/mis-typed fields",
      "Output that is too short",
      "Output in the wrong font",
    ],
    a: 1,
    e: "Malformed output is structurally broken: invalid JSON, missing required fields, or wrong types.",
  },
  {
    c: "Malformed output handling", cat: "debugging", t: "debugging", d: "medium",
    q: "Your parser throws on the model's JSON ~2% of the time. Best production handling?",
    o: [
      "Crash and alert the user",
      "Catch the parse error and re-prompt or repair, with a bounded number of attempts",
      "Ignore and return an empty object",
      "Assume it never happens",
    ],
    a: 1,
    e: "Occasional malformed JSON should be caught and recovered (re-prompt/repair) within bounded attempts. Crashing, ignoring, or assuming perfection are all unsafe.",
  },
  {
    c: "Schema validation", cat: "application", t: "application", d: "medium",
    q: "You want the `type` field to only ever be one of a fixed set. What schema feature expresses this?",
    o: [
      "A regular string type",
      "An enum",
      "A number type",
      "A nullable field",
    ],
    a: 1,
    e: "An enum restricts a field to a fixed set of allowed values, enforcing it at the schema level.",
  },
  {
    c: "Structured output", cat: "application", t: "scenario", d: "medium",
    q: "For the future system, converting a thesis to constraints should output:",
    o: [
      "A free-form paragraph",
      "Typed JSON constraints (e.g. `{type, sector, value}`) suitable for a deterministic checker",
      "An image",
      "A single number",
    ],
    a: 1,
    e: "Downstream deterministic checks require typed structured constraints, not prose, so the constraint engine can operate on them.",
  },
  {
    c: "Business-rule validation", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Which failure is specifically 'schema-valid but semantically invalid'?",
    o: [
      "Missing required field",
      "Wrong JSON syntax",
      "A weight of 1.5 where weights must be in [0,1]",
      "`type` field absent",
    ],
    a: 2,
    e: "1.5 is a valid number (schema passes) but violates the [0,1] business rule. The others are schema-level failures.",
  },
  {
    c: "Schema validation", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Which is a schema-level concern?",
    o: [
      "Whether a sector weight is economically sensible",
      "Whether a required field is present and correctly typed",
      "Whether two constraints contradict",
      "Whether the thesis is a good investment",
    ],
    a: 1,
    e: "Presence and type are schema concerns. Economic sensibility and contradiction detection are business/consistency concerns.",
  },
  {
    c: "Business-rule validation", cat: "architecture", t: "architecture", d: "hard",
    q: "How should you order validation layers for robustness?",
    o: [
      "Business rules first, then parse JSON",
      "Parse/schema-validate first, then business-rule validation, then cross-constraint consistency",
      "Only business validation",
      "Only schema validation",
    ],
    a: 1,
    e: "Validate in increasing semantic depth: parse & schema (shape), then business rules (values), then cross-constraint consistency (contradictions). Each layer assumes the previous passed.",
  },
  {
    c: "Malformed output handling", cat: "application", t: "scenario", d: "medium",
    q: "A required field is occasionally missing from the model's JSON. Which is the most robust safeguard?",
    o: [
      "Trust the model to always include it",
      "Validate required fields and, on failure, re-prompt with the specific missing field named",
      "Fill it with a random value",
      "Remove the field from the schema",
    ],
    a: 1,
    e: "Explicitly validating required fields and re-prompting with the specific gap is robust and self-correcting. Trusting, randomizing, or dropping the field are unsafe.",
  },
  {
    c: "Structured output", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Which is TRUE about forcing structured output?",
    o: [
      "It guarantees the content is correct",
      "It improves the reliability of the output's shape but not its semantic correctness",
      "It removes the need for any validation",
      "It slows the model to a crawl",
    ],
    a: 1,
    e: "Structured-output features make the shape reliable; semantic correctness still needs validation.",
  },
  {
    c: "Schema validation", cat: "debugging", t: "debugging", d: "medium",
    q: "A downstream function expects `value: number` but sometimes receives `value: \"0.25\"` (a string). Where to fix?",
    o: [
      "Ignore the type; JS will coerce it",
      "Enforce the number type in the schema/validation and reject or coerce explicitly at the boundary",
      "Change the function to accept anything",
      "Raise temperature",
    ],
    a: 1,
    e: "Type drift (string vs number) must be caught at the validation boundary and handled explicitly. Relying on implicit coercion invites subtle bugs.",
  },
  {
    c: "Malformed output handling", cat: "debugging", t: "failure-mode", d: "easy",
    q: "Which is NOT a structured-output failure mode?",
    o: [
      "Malformed JSON",
      "Missing required field",
      "Wrong type for a field",
      "Correct, well-typed JSON that satisfies all rules",
    ],
    a: 3,
    e: "Valid, rule-satisfying JSON is success, not a failure. The others are genuine failure modes.",
  },
  {
    c: "Business-rule validation", cat: "application", t: "application", d: "medium",
    q: "For a set of sector weights that must sum to ≤ 1.0, this check is:",
    o: [
      "A schema check",
      "A business/consistency check across fields",
      "A parsing check",
      "An enum check",
    ],
    a: 1,
    e: "Summing constraints across fields is a business/consistency rule, beyond per-field schema validation.",
  },
  {
    c: "Structured output", cat: "architecture", t: "architecture", d: "hard",
    q: "Why put the validation layer between the LLM and the deterministic engine, rather than inside the engine?",
    o: [
      "To keep the engine's inputs trustworthy and localize LLM-error handling at the boundary",
      "To make the engine slower",
      "Because engines can't read JSON",
      "To avoid using schemas",
    ],
    a: 0,
    e: "A boundary validator keeps the deterministic engine's inputs clean and concentrates LLM-error handling in one place, so the engine can assume valid inputs.",
  },
  {
    c: "Schema validation", cat: "conceptual", t: "conceptual", d: "easy",
    q: "An enum with values ['sector_max','sector_min','position_max'] ensures:",
    o: [
      "The value is a number",
      "The `type` field can only be one of those three strings",
      "The field is optional",
      "The output is sorted",
    ],
    a: 1,
    e: "An enum restricts the field to the listed allowed values, rejecting anything else at schema time.",
  },
  {
    c: "Business-rule validation", cat: "debugging", t: "debugging", d: "hard",
    q: "The model outputs `{type:'sector_min', sector:'Tech', value:0.4}` and `{type:'sector_max', sector:'Tech', value:0.25}`. Both individually valid. What should the validator report?",
    o: [
      "Nothing; both are valid",
      "A contradiction: Tech min (0.40) exceeds Tech max (0.25) — infeasible by 15 percentage points",
      "A JSON syntax error",
      "A missing field",
    ],
    a: 1,
    e: "Cross-constraint validation must catch that min>max for the same sector — a contradiction quantifiable as a 15pp gap. This foreshadows Day 8 feasibility.",
  },
  {
    c: "Malformed output handling", cat: "application", t: "scenario", d: "medium",
    q: "Which practice most reduces malformed structured output in the first place?",
    o: [
      "Vague instructions",
      "Using the provider's structured-output/JSON-schema features plus a clear target schema",
      "Higher temperature",
      "Longer prompts full of unrelated text",
    ],
    a: 1,
    e: "Provider structured-output features with an explicit schema make conformant output far more reliable, reducing malformed cases before recovery is even needed.",
    ref: "OpenAI/Anthropic structured output docs",
  },
  {
    c: "Structured output", cat: "conceptual", t: "conceptual", d: "medium",
    q: "The main risk of assuming 'structured = correct' is:",
    o: [
      "Slower responses",
      "Acting on well-shaped but semantically wrong data as if it were verified",
      "Higher token cost",
      "Larger files",
    ],
    a: 1,
    e: "Conflating shape with correctness leads to trusting well-formed but wrong data — exactly what business validation exists to prevent.",
  },
  {
    c: "Schema validation", cat: "debugging", t: "failure-mode", d: "medium",
    q: "A field defined as required is sometimes null. This is caught by:",
    o: [
      "Business validation only",
      "Schema validation (required/non-null constraint)",
      "The deterministic engine",
      "The embedding step",
    ],
    a: 1,
    e: "Required/non-null is a schema constraint; a null in a required field is a schema-level failure.",
  },
  {
    c: "Business-rule validation", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Business-rule validation is necessary because:",
    o: [
      "Schemas cannot express all semantic constraints",
      "JSON is insecure",
      "Models never make mistakes",
      "It replaces schema validation",
    ],
    a: 0,
    e: "Schemas capture shape but not all domain semantics (ranges, relationships, feasibility), so business validation complements — not replaces — it.",
  },
]);
