import { bank } from "./_builder";

// Day 5 — State, Memory & Orchestration (25 questions)
export const day5 = bank("day-5", "State, Memory & Orchestration", [
  {
    c: "State", cat: "conceptual", t: "conceptual", d: "easy",
    q: "In a multi-step workflow, 'state' is:",
    o: [
      "The model's training data",
      "The information carried from one step to the next during a run",
      "The GPU memory",
      "The temperature",
    ],
    a: 1,
    e: "State is the working information passed between steps within a single run of a workflow.",
  },
  {
    c: "State", cat: "conceptual", t: "conceptual", d: "medium",
    q: "How does state differ from memory?",
    o: [
      "They are identical",
      "State is within-run working data; memory is information retained beyond the immediate step/context",
      "Memory is faster than state",
      "State only exists in multi-agent systems",
    ],
    a: 1,
    e: "State is the working data of the current run; memory persists beyond the immediate context (across turns/runs). Conflating them is a common mistake.",
  },
  {
    c: "Memory", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Which statement about memory is correct?",
    o: [
      "Every agent must have persistent long-term memory",
      "Memory should be added when the task genuinely needs information retained across contexts, not by default",
      "Memory is the same as the system prompt",
      "Memory eliminates the need for state",
    ],
    a: 1,
    e: "Persistent memory adds complexity and should be introduced only when needed. Not every agent requires it.",
  },
  {
    c: "Orchestration", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Orchestration in agent systems refers to:",
    o: [
      "The control logic deciding the order/flow of steps",
      "The embedding model",
      "The database schema",
      "The temperature schedule",
    ],
    a: 0,
    e: "Orchestration is the control flow: sequential, parallel, or conditional execution of steps.",
  },
  {
    c: "Orchestration", cat: "application", t: "scenario", d: "medium",
    q: "Two independent sub-tasks don't depend on each other's output. Which orchestration is most efficient?",
    o: [
      "Sequential",
      "Parallel",
      "Conditional",
      "A single LLM call that does both implicitly",
    ],
    a: 1,
    e: "Independent tasks can run in parallel to reduce latency. Sequencing them wastes time; conditional branching isn't needed since both always run.",
  },
  {
    c: "Orchestration", cat: "application", t: "scenario", d: "medium",
    q: "Step B needs Step A's output. Which orchestration is required?",
    o: [
      "Parallel",
      "Sequential (A then B)",
      "Random",
      "They can't be combined",
    ],
    a: 1,
    e: "A data dependency forces sequential execution: A must complete before B can use its output.",
  },
  {
    c: "Orchestration", cat: "application", t: "scenario", d: "medium",
    q: "You only want to run a Risk step when Research finds a candidate. This is:",
    o: [
      "Parallel orchestration",
      "Conditional (branching) orchestration",
      "Memory",
      "A schema check",
    ],
    a: 1,
    e: "Running a step only when a condition holds is conditional/branching orchestration.",
  },
  {
    c: "Retries & termination", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Why does a workflow need a termination condition?",
    o: [
      "To make it prettier",
      "To ensure it stops instead of running or looping forever",
      "To reduce token size",
      "To choose a model",
    ],
    a: 1,
    e: "Without explicit termination, loops/workflows can hang or run forever. Termination guarantees the process ends.",
  },
  {
    c: "Retries & termination", cat: "debugging", t: "debugging", d: "hard",
    q: "A workflow occasionally never finishes. Logs show a step's success condition is never met, so it retries endlessly. Best fix?",
    o: [
      "Remove logging",
      "Bound the retries and define an explicit failure/termination path when the condition can't be met",
      "Increase temperature",
      "Add more steps",
    ],
    a: 1,
    e: "Unbounded retries on an unmeetable condition cause hangs. Bound retries and define what happens on give-up (fail/terminate gracefully).",
  },
  {
    c: "State", cat: "debugging", t: "debugging", d: "medium",
    q: "Step C reads a value Step A wrote, but gets stale/wrong data. Most likely cause?",
    o: [
      "The embedding model changed",
      "State is being mutated/overwritten between steps or not passed explicitly",
      "The temperature is too low",
      "There are too many tools",
    ],
    a: 1,
    e: "Corrupted/overwritten state or implicit shared mutation is the usual cause of stale reads. Passing state explicitly and avoiding hidden mutation fixes it.",
  },
  {
    c: "State", cat: "architecture", t: "architecture", d: "hard",
    q: "Which design most reduces state bugs in a multi-step workflow?",
    o: [
      "A single global mutable variable everything edits",
      "Passing an explicit state object forward, with steps reading only what earlier steps wrote",
      "No state at all",
      "Storing state only in the prompt text",
    ],
    a: 1,
    e: "Explicit, forward-passed state with clear read/write boundaries makes data flow legible and reduces accidental mutation bugs. Global mutable state invites corruption.",
  },
  {
    c: "Memory", cat: "application", t: "scenario", d: "medium",
    q: "A support agent must recall a user's past tickets across sessions. This requires:",
    o: [
      "Only within-run state",
      "Persistent memory that survives beyond a single run",
      "A larger context window only",
      "Higher temperature",
    ],
    a: 1,
    e: "Cross-session recall needs persistent memory, not just within-run state. A bigger context window alone doesn't persist across separate runs.",
  },
  {
    c: "Orchestration", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Which is a parallel-orchestration failure mode?",
    o: [
      "A race condition where branches write shared state unpredictably",
      "A single deterministic function call",
      "Reading a schema",
      "A clear termination condition",
    ],
    a: 0,
    e: "Parallel branches touching shared state can race, producing nondeterministic results. This is a classic parallel-orchestration hazard.",
  },
  {
    c: "Retries & termination", cat: "application", t: "scenario", d: "medium",
    q: "A transient network step fails ~10% of the time. Best retry policy?",
    o: [
      "No retries",
      "Bounded retries with backoff, then fail gracefully",
      "Infinite retries",
      "Retry only after restarting the whole workflow",
    ],
    a: 1,
    e: "Bounded retries with backoff handle transience without risking infinite loops, and a graceful failure covers persistent problems.",
  },
  {
    c: "Orchestration", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Which best distinguishes a fixed workflow from an autonomous agent?",
    o: [
      "Workflows use no LLM steps",
      "In a workflow the control flow is predetermined; an agent decides the flow at runtime based on observations",
      "Agents are always faster",
      "Workflows cannot have branches",
    ],
    a: 1,
    e: "Workflows have predetermined control flow (which can include branches and LLM steps); agents choose their path at runtime. Deciding flow at runtime is the key difference.",
  },
  {
    c: "State", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Conversation history passed between turns is an example of:",
    o: [
      "A tool",
      "State (short-term working context)",
      "An embedding",
      "A schema",
    ],
    a: 1,
    e: "The running conversation history is short-term state carried across turns of the interaction.",
  },
  {
    c: "Retries & termination", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Which is a 'termination failure'?",
    o: [
      "A workflow ends after producing its result",
      "The stopping condition is never satisfied so the process never ends",
      "A step returns early on success",
      "A branch is skipped by design",
    ],
    a: 1,
    e: "A termination failure is when the stop condition is never met, so the process never ends. Ending on success or skipping a branch by design are normal.",
  },
  {
    c: "Orchestration", cat: "architecture", t: "architecture", d: "hard",
    q: "For Research → Risk → Summary where Summary needs both prior outputs, which is the cleanest design?",
    o: [
      "Run all three in parallel and hope ordering works out",
      "Sequential with an explicit state object accumulating each step's output for Summary to read",
      "A single prompt that does everything with no state",
      "Conditional skipping of Summary",
    ],
    a: 1,
    e: "Because Summary depends on both prior steps, sequential execution with an explicit accumulating state object is cleanest and correct.",
  },
  {
    c: "Memory", cat: "debugging", t: "failure-mode", d: "medium",
    q: "A risk of adding persistent memory prematurely is:",
    o: [
      "Faster responses",
      "Added complexity, stale/irrelevant recall, and harder debugging without a real need",
      "Guaranteed correctness",
      "Smaller prompts",
    ],
    a: 1,
    e: "Premature memory adds complexity and can surface stale or irrelevant information, complicating debugging — with no benefit if the task didn't need it.",
  },
  {
    c: "State", cat: "application", t: "application", d: "medium",
    q: "To debug how state evolves, you should:",
    o: [
      "Print/inspect the state object at the entry and exit of each step",
      "Only log the final answer",
      "Disable all steps",
      "Increase temperature",
    ],
    a: 0,
    e: "Inspecting state at each step boundary reveals exactly where data is added, read, or corrupted.",
  },
  {
    c: "Orchestration", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Sequential, parallel, and conditional are three kinds of:",
    o: [
      "Embeddings",
      "Orchestration/control flow",
      "Tools",
      "Schemas",
    ],
    a: 1,
    e: "They are the basic shapes of orchestration (control flow).",
  },
  {
    c: "Retries & termination", cat: "conceptual", t: "conceptual", d: "easy",
    q: "A bounded retry means:",
    o: [
      "Retrying forever until success",
      "Retrying at most a fixed number of times before giving up",
      "Never retrying",
      "Retrying with increasing temperature",
    ],
    a: 1,
    e: "A bounded retry caps the number of attempts, preventing infinite loops while still handling transient failures.",
  },
  {
    c: "Memory", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Which is the clearest example of memory (not just state)?",
    o: [
      "The current step's intermediate result",
      "A stored user preference reused in a future, separate session",
      "The prompt for this call",
      "A tool's return value this run",
    ],
    a: 1,
    e: "A preference reused across separate sessions is persistent memory. The others are within-run state.",
  },
  {
    c: "Orchestration", cat: "debugging", t: "debugging", d: "hard",
    q: "In a parallel fan-out/fan-in, results are sometimes dropped. Most likely cause?",
    o: [
      "The aggregation step doesn't correctly wait for and merge all branch results",
      "The embeddings are stale",
      "The schema is too strict",
      "The temperature is too high",
    ],
    a: 0,
    e: "Dropped results in fan-in usually mean the aggregation isn't awaiting/merging every branch correctly (a synchronization bug), not an embedding or schema issue.",
  },
  {
    c: "State", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Passing state 'explicitly' rather than via globals mainly improves:",
    o: [
      "Model accuracy",
      "Traceability and reduced accidental mutation",
      "Embedding quality",
      "Token cost",
    ],
    a: 1,
    e: "Explicit state passing makes data flow traceable and prevents hidden mutations, improving correctness and debuggability.",
  },
]);
