import { bank } from "./_builder";

// Day 6 — Multi-Agent Systems (30 questions)
export const day6 = bank("day-6", "Multi-Agent Systems", [
  {
    c: "Multi-agent value", cat: "conceptual", t: "conceptual", d: "easy",
    q: "What can multiple specialized agents add over a single agent?",
    o: [
      "Guaranteed lower cost",
      "Specialization, parallelism, and independent perspectives/criticism",
      "Removal of all failure modes",
      "Deterministic output",
    ],
    a: 1,
    e: "Multiple agents can specialize, work in parallel, and offer independent perspectives. They do not lower cost or remove failure modes.",
  },
  {
    c: "Multi-agent value", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Which is a legitimate reason to use multiple agents?",
    o: [
      "It looks more sophisticated",
      "Distinct roles genuinely need different objectives/expertise or independent review",
      "To use more tokens",
      "To avoid writing schemas",
    ],
    a: 1,
    e: "Multi-agent is justified when roles genuinely differ or independent review adds value — not for appearance or token usage.",
  },
  {
    c: "Coordination", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Coordination between agents primarily involves:",
    o: [
      "Sharing state and combining outputs",
      "Choosing an embedding model",
      "Setting the temperature",
      "Writing a schema",
    ],
    a: 0,
    e: "Coordination is about how agents share state and how their outputs are combined/aggregated.",
  },
  {
    c: "Coordination", cat: "application", t: "scenario", d: "medium",
    q: "Three agents each produce a partial result. What must the system have to produce a coherent final output?",
    o: [
      "Nothing; they self-organize",
      "An explicit aggregation/coordination strategy",
      "A larger model",
      "More tools",
    ],
    a: 1,
    e: "Agents don't self-organize; an explicit aggregation strategy is needed to combine partial results coherently.",
  },
  {
    c: "Conflict & aggregation", cat: "conceptual", t: "conceptual", d: "medium",
    q: "When two agents disagree, a good committee design should:",
    o: [
      "Silently average their outputs",
      "Surface and reason about the disagreement, not hide it",
      "Pick the longer answer",
      "Discard both",
    ],
    a: 1,
    e: "Silent averaging hides meaningful disagreement. A good design surfaces the conflict so it can be reasoned about.",
  },
  {
    c: "Conflict & aggregation", cat: "application", t: "scenario", d: "hard",
    q: "Research says 'strong buy', Risk says 'high downside'. The committee outputs a blended score of 5/10 with no explanation. What's wrong?",
    o: [
      "Nothing, averaging is ideal",
      "It silently averaged away a material conflict that a decision-maker needs to see",
      "It used too few agents",
      "It used the wrong embedding model",
    ],
    a: 1,
    e: "Blending a bullish and bearish view into a bland number hides the exact conflict the decision-maker must weigh. The disagreement should be surfaced explicitly.",
  },
  {
    c: "Multi-agent cost", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Adding more agents typically increases:",
    o: [
      "Determinism",
      "Latency, cost, and coordination complexity",
      "Accuracy, always",
      "Simplicity",
    ],
    a: 1,
    e: "Each agent adds latency, cost, and coordination complexity; accuracy is not guaranteed to improve.",
  },
  {
    c: "Multi-agent cost", cat: "application", t: "scenario", d: "medium",
    q: "A single agent solves the task well in 2s. A five-agent version takes 11s and costs 5x for the same quality. What should you do?",
    o: [
      "Keep the five agents; more is better",
      "Use the single agent — the multi-agent cost isn't justified by any quality gain",
      "Add a sixth agent",
      "Increase temperature",
    ],
    a: 1,
    e: "If multi-agent adds latency and cost without quality benefit, the single agent wins. Complexity must be justified by value.",
  },
  {
    c: "When not to use multiple agents", cat: "conceptual", t: "conceptual", d: "medium",
    q: "When should you NOT use multiple agents?",
    o: [
      "When a single agent or workflow suffices",
      "When the task has distinct expert roles",
      "When independent review adds real value",
      "When subtasks are truly parallelizable and beneficial",
    ],
    a: 0,
    e: "If one agent or a workflow suffices, multiple agents just add cost and failure surface. The other cases can justify multi-agent.",
  },
  {
    c: "When not to use multiple agents", cat: "application", t: "scenario", d: "medium",
    q: "A team splits a simple summarization into 4 agents (reader, summarizer, editor, formatter) and quality drops due to coordination errors. Best fix?",
    o: [
      "Add a 5th coordinator agent",
      "Collapse to a single well-instructed agent/call for this simple task",
      "Increase temperature",
      "Add memory",
    ],
    a: 1,
    e: "Over-decomposing a simple task multiplies coordination failure. Collapsing to one agent removes the overhead and errors.",
  },
  {
    c: "Multi-agent value", cat: "architecture", t: "architecture", d: "hard",
    q: "For the future Investment Committee, why separate Research, Macro, and Risk into distinct agents?",
    o: [
      "To use more compute",
      "Because they have genuinely different objectives and independent perspectives improve the decision",
      "Because single agents can't call tools",
      "To avoid structured outputs",
    ],
    a: 1,
    e: "Distinct objectives and the value of independent perspectives justify specialization here. It's not about compute or tool limitations.",
  },
  {
    c: "Coordination", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Two agents redundantly do the same work. This is a failure of:",
    o: [
      "Coordination (roles/tasks not clearly partitioned)",
      "Embedding quality",
      "Schema validation",
      "Termination",
    ],
    a: 0,
    e: "Redundant work signals poor coordination — roles/tasks weren't clearly partitioned.",
  },
  {
    c: "Conflict & aggregation", cat: "architecture", t: "architecture", d: "hard",
    q: "Which aggregation approach best preserves decision quality under disagreement?",
    o: [
      "Always average numeric outputs",
      "Record each agent's position and rationale, then reconcile with an explicit policy (e.g. surface conflict, defer to risk on safety)",
      "Take the first agent's answer",
      "Randomly pick one",
    ],
    a: 1,
    e: "Capturing positions + rationales and applying an explicit reconciliation policy preserves information and produces defensible decisions. Averaging/first/random discard signal.",
  },
  {
    c: "Multi-agent cost", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Communication overhead in multi-agent systems refers to:",
    o: [
      "The cost of the physical network cable",
      "Extra latency/tokens spent passing messages and context between agents",
      "The embedding dimension",
      "The number of schemas",
    ],
    a: 1,
    e: "Communication overhead is the added latency and token cost of agents exchanging context/messages, which grows with the number of agents.",
  },
  {
    c: "When not to use multiple agents", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Using multiple agents is best understood as:",
    o: [
      "A requirement for serious systems",
      "A design choice to be justified by value, not a default",
      "Always the fastest option",
      "A way to avoid validation",
    ],
    a: 1,
    e: "Multi-agent is a design choice justified by value — echoing the Day 1 lesson that agents themselves are a choice, not a requirement.",
  },
  {
    c: "Multi-agent value", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Independent 'criticism' between agents can help by:",
    o: [
      "Guaranteeing correctness",
      "Catching errors one agent alone might miss via a reviewer/critic role",
      "Reducing latency",
      "Removing the need for tools",
    ],
    a: 1,
    e: "A critic/reviewer agent can catch mistakes a single agent misses, improving quality — though it adds latency and doesn't guarantee correctness.",
  },
  {
    c: "Coordination", cat: "application", t: "scenario", d: "medium",
    q: "Agents need to build on each other's findings. What shared mechanism supports this?",
    o: [
      "A shared/passed state accessible to the relevant agents",
      "Higher temperature",
      "A larger embedding model",
      "More enums",
    ],
    a: 0,
    e: "Shared or passed state lets agents build on each other's work in a coordinated way.",
  },
  {
    c: "Conflict & aggregation", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Silent averaging of conflicting agent outputs is problematic because it:",
    o: [
      "Is too slow",
      "Hides the disagreement decision-makers need to see",
      "Uses too few tokens",
      "Requires a schema",
    ],
    a: 1,
    e: "Averaging conflicting views conceals the disagreement, removing information critical to a good decision.",
  },
  {
    c: "Multi-agent cost", cat: "application", t: "scenario", d: "hard",
    q: "Latency is unacceptable in a 6-agent sequential pipeline. Which change most reduces latency without losing needed roles?",
    o: [
      "Run independent agents in parallel and only sequence true dependencies",
      "Add more agents",
      "Increase temperature",
      "Remove all agents",
    ],
    a: 0,
    e: "Parallelizing independent agents while sequencing only genuine dependencies cuts latency while keeping the roles that matter.",
  },
  {
    c: "When not to use multiple agents", cat: "debugging", t: "failure-mode", d: "medium",
    q: "A symptom of unnecessary multi-agent complexity is:",
    o: [
      "Lower cost than a single call",
      "Coordination bugs and inconsistent state for a task one agent could do",
      "Fewer failure modes",
      "Deterministic outputs",
    ],
    a: 1,
    e: "When a task one agent could handle instead suffers coordination bugs and inconsistent state, the multi-agent design was unnecessary.",
  },
  {
    c: "Coordination", cat: "debugging", t: "debugging", d: "hard",
    q: "In a committee, agents sometimes act on stale versions of a shared document. Root cause?",
    o: [
      "Shared state updates aren't synchronized/ordered, so agents read outdated data",
      "The embedding model is wrong",
      "The schema has too many fields",
      "Temperature is too low",
    ],
    a: 0,
    e: "Stale reads of shared state indicate a synchronization/ordering problem in how updates are propagated between agents.",
  },
  {
    c: "Multi-agent value", cat: "application", t: "scenario", d: "medium",
    q: "Which task most clearly benefits from multiple specialized agents?",
    o: [
      "Converting Celsius to Fahrenheit",
      "A research decision requiring separate deep research, macro analysis, and risk critique",
      "Reversing a string",
      "Looking up a value by exact ID",
    ],
    a: 1,
    e: "A decision needing genuinely different expert perspectives benefits from specialization. The others are trivial/deterministic single-step tasks.",
  },
  {
    c: "Conflict & aggregation", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Which is a coordination/conflict failure, not a tool failure?",
    o: [
      "A tool times out",
      "Agents produce contradictory conclusions with no reconciliation policy",
      "A schema mismatch on a tool call",
      "An API is unavailable",
    ],
    a: 1,
    e: "Contradictory conclusions without reconciliation is a coordination/conflict failure. The others are tool-level failures.",
  },
  {
    c: "Multi-agent cost", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Compared to one agent, a multi-agent system generally has:",
    o: [
      "A larger failure surface",
      "A smaller failure surface",
      "No failure surface",
      "Identical complexity",
    ],
    a: 0,
    e: "More agents and communication mean more places to fail — a larger failure surface and more complexity.",
  },
  {
    c: "When not to use multiple agents", cat: "architecture", t: "architecture", d: "hard",
    q: "You're deciding single-agent vs multi-agent. Which factor most favors multi-agent?",
    o: [
      "You want to use JSON",
      "The problem decomposes into genuinely distinct roles whose independent work/critique improves outcomes enough to justify the overhead",
      "You have a vector database",
      "The output must be a number",
    ],
    a: 1,
    e: "Multi-agent is favored when real role decomposition and independent critique add enough value to outweigh coordination overhead. Data formats/stores don't decide this.",
  },
  {
    c: "Coordination", cat: "conceptual", t: "conceptual", d: "medium",
    q: "'Aggregation' in a multi-agent system means:",
    o: [
      "Deleting agent outputs",
      "Combining multiple agents' outputs into a coherent result",
      "Embedding the outputs",
      "Validating JSON",
    ],
    a: 1,
    e: "Aggregation is the step that combines agents' outputs into a single coherent result.",
  },
  {
    c: "Multi-agent value", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Parallelism in multi-agent systems helps most when:",
    o: [
      "Subtasks are independent",
      "Subtasks strictly depend on each other",
      "There is only one subtask",
      "The output must be deterministic",
    ],
    a: 0,
    e: "Parallelism helps when subtasks are independent so they can run at the same time. Dependent subtasks must be sequenced.",
  },
  {
    c: "Conflict & aggregation", cat: "application", t: "scenario", d: "medium",
    q: "The Day 6 build deliberately creates disagreement so you can practice:",
    o: [
      "Ignoring conflict",
      "Surfacing and reconciling conflict explicitly rather than blending it away",
      "Choosing embeddings",
      "Writing schemas",
    ],
    a: 1,
    e: "Engineering a disagreement forces you to practice surfacing and reconciling conflict — the core Day 6 skill.",
  },
  {
    c: "Multi-agent cost", cat: "debugging", t: "debugging", d: "medium",
    q: "Token costs exploded after moving to multi-agent. What commonly drives this?",
    o: [
      "Each agent re-receiving large shared context/messages on every step",
      "Using a schema",
      "Lower temperature",
      "Fewer tools",
    ],
    a: 0,
    e: "Repeatedly passing large context/messages to each agent multiplies token usage — a common multi-agent cost driver. Trimming shared context helps.",
  },
  {
    c: "When not to use multiple agents", cat: "application", t: "scenario", d: "medium",
    q: "A committee agent must reconcile a bullish Research view and a bearish Risk view for a decision-maker. Best output design?",
    o: [
      "A single blended number with no rationale",
      "A structured decision that states both positions, the disagreement, and the reasoning for the final call",
      "Only the Research view, since it was first",
      "A random pick between the two",
    ],
    a: 1,
    e: "Preserving both positions and the reasoning behind the final call gives the decision-maker the conflict they need to weigh — far better than a blended number or an arbitrary pick.",
  },
]);
