import { bank } from "./_builder";

// Day 7 — Frameworks & Fetch/uAgents (25 questions)
export const day7 = bank("day-7", "Frameworks & uAgents", [
  {
    c: "Framework tradeoffs", cat: "conceptual", t: "conceptual", d: "easy",
    q: "What is the smart way to learn multiple agent frameworks quickly?",
    o: [
      "Memorize every API of each",
      "Grasp the shared axes: orchestration, tools, state, agents, and communication",
      "Only read marketing pages",
      "Avoid all of them",
    ],
    a: 1,
    e: "Frameworks vary along the same axes (orchestration, tools, state, communication). Understanding those axes lets you learn any framework fast without memorizing every API.",
  },
  {
    c: "Framework tradeoffs", cat: "conceptual", t: "conceptual", d: "medium",
    q: "LangGraph's distinctive conceptual model is best described as:",
    o: [
      "A role/crew abstraction",
      "Explicit stateful graphs (nodes/edges) with controllable state",
      "A decentralized messaging network",
      "A no-code drag-and-drop builder only",
    ],
    a: 1,
    e: "LangGraph models agents/workflows as explicit stateful graphs with nodes, edges, and controllable state.",
    ref: "LangGraph docs",
  },
  {
    c: "Framework tradeoffs", cat: "conceptual", t: "conceptual", d: "medium",
    q: "CrewAI's distinctive abstraction centers on:",
    o: [
      "Cryptographic agent addresses",
      "Roles, tasks, and crews collaborating",
      "Vector databases",
      "Schema validation",
    ],
    a: 1,
    e: "CrewAI centers on roles, tasks, and crews — a role-based collaboration abstraction.",
    ref: "CrewAI docs",
  },
  {
    c: "Framework tradeoffs", cat: "application", t: "scenario", d: "medium",
    q: "You need fine-grained control over state and branching in a complex workflow. Which framework style fits best?",
    o: [
      "An explicit stateful-graph framework (e.g. LangGraph)",
      "A pure single-call API with no orchestration",
      "A framework that hides all state",
      "None can express branching",
    ],
    a: 0,
    e: "Fine-grained state and branching control maps well to an explicit stateful-graph framework. Hiding state or using a single call won't give that control.",
  },
  {
    c: "Framework tradeoffs", cat: "conceptual", t: "conceptual", d: "medium",
    q: "The OpenAI Agents SDK is best characterized as:",
    o: [
      "A heavyweight enterprise service bus",
      "A lightweight agent loop with tools and handoffs",
      "A vector database",
      "A charting library",
    ],
    a: 1,
    e: "The OpenAI Agents SDK provides a lightweight agent loop with tools and handoffs between agents.",
  },
  {
    c: "uAgent identity & addresses", cat: "conceptual", t: "conceptual", d: "easy",
    q: "In Fetch's uAgents, how does one agent reach another?",
    o: [
      "By importing its Python function directly",
      "By sending a message to the other agent's address",
      "By editing its weights",
      "By sharing a global variable",
    ],
    a: 1,
    e: "uAgents communicate by sending messages to each other's addresses, not by direct function import.",
    ref: "uAgents docs",
  },
  {
    c: "uAgent identity & addresses", cat: "conceptual", t: "conceptual", d: "medium",
    q: "A uAgent's identity is backed by:",
    o: [
      "A random session cookie",
      "A cryptographic key pair that yields its unique address",
      "Its process ID",
      "Its file path",
    ],
    a: 1,
    e: "Each uAgent has a cryptographic identity (key pair) that produces its unique, stable address.",
  },
  {
    c: "uAgent identity & addresses", cat: "application", t: "scenario", d: "medium",
    q: "Agent A must message Agent B. What does A need?",
    o: [
      "B's source code",
      "B's address (and a shared message model)",
      "B's GPU",
      "B's training data",
    ],
    a: 1,
    e: "A needs B's address to route the message and a shared/compatible message model so B can decode it.",
  },
  {
    c: "Agent messaging & protocols", cat: "conceptual", t: "conceptual", d: "easy",
    q: "uAgents exchange:",
    o: [
      "Unstructured free text only",
      "Typed messages (models), optionally organized into protocols",
      "Raw GPU tensors",
      "Database rows",
    ],
    a: 1,
    e: "uAgents exchange typed message models, which can be organized into protocols defining message flows.",
  },
  {
    c: "Agent messaging & protocols", cat: "conceptual", t: "conceptual", d: "medium",
    q: "A 'protocol' in uAgents primarily provides:",
    o: [
      "A way to speed up embeddings",
      "A defined set of message types/flows so communication is predictable and discoverable",
      "A vector index",
      "A prompt template",
    ],
    a: 1,
    e: "A protocol defines message types and their flow, making inter-agent communication predictable and discoverable.",
  },
  {
    c: "Agent messaging & protocols", cat: "debugging", t: "debugging", d: "hard",
    q: "Agent B silently ignores A's messages. The addresses are correct. Most likely cause?",
    o: [
      "B's temperature is too low",
      "A message-model mismatch — B doesn't have a handler for A's message type/model",
      "The embedding model is wrong",
      "There are too many tools",
    ],
    a: 1,
    e: "With correct addressing, silent drops usually mean B lacks a handler for that message model, or the models don't match. Temperature/embeddings are irrelevant to message routing.",
  },
  {
    c: "Framework tradeoffs", cat: "architecture", t: "architecture", d: "hard",
    q: "You want decentralized agents that can be discovered and message each other across systems. Which ecosystem fits best?",
    o: [
      "A single-process orchestration library only",
      "Fetch/uAgents with addresses and Agentverse for discovery",
      "A local function-call graph",
      "A spreadsheet",
    ],
    a: 1,
    e: "Decentralized, discoverable, message-passing agents map to Fetch/uAgents + Agentverse. A single-process library or local call graph doesn't provide cross-system discovery.",
    ref: "Fetch.ai / Agentverse",
  },
  {
    c: "uAgent identity & addresses", cat: "conceptual", t: "conceptual", d: "easy",
    q: "What is Agentverse, at a high level?",
    o: [
      "A charting tool",
      "A platform to host, register, and discover uAgents",
      "A vector database",
      "A prompt library",
    ],
    a: 1,
    e: "Agentverse is Fetch's platform for hosting and discovering uAgents.",
    ref: "agentverse.ai",
  },
  {
    c: "Framework tradeoffs", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Google's ADK is best described as:",
    o: [
      "A framework for building agents within the Google ecosystem",
      "A Fetch messaging protocol",
      "A chunking algorithm",
      "A JSON schema validator",
    ],
    a: 0,
    e: "Google's Agent Development Kit (ADK) is for building agents in the Google ecosystem. The others are unrelated categories.",
  },
  {
    c: "Framework tradeoffs", cat: "application", t: "scenario", d: "medium",
    q: "A colleague insists you must master all four frameworks before building anything. Better guidance?",
    o: [
      "Agree; master them all first",
      "Learn the shared axes, pick one that fits the task, and build — deep-dive others as needed",
      "Avoid frameworks entirely",
      "Only use whichever is newest",
    ],
    a: 1,
    e: "Understanding the shared axes and choosing a fitting framework to build with beats trying to master everything up front.",
  },
  {
    c: "Agent messaging & protocols", cat: "application", t: "scenario", d: "medium",
    q: "For the Day 7 build, the minimal success criterion is:",
    o: [
      "Deploy to production with billing",
      "Agent A sends a message to Agent B, B replies, and both addresses are printed",
      "Train a new model",
      "Build a full RAG system",
    ],
    a: 1,
    e: "The minimal build is a local request/response round-trip between two uAgents with their addresses printed.",
  },
  {
    c: "Framework tradeoffs", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Which is a framework-choice failure mode?",
    o: [
      "Picking a heavyweight framework for a trivial task, adding needless complexity",
      "Using a schema",
      "Printing logs",
      "Returning JSON",
    ],
    a: 0,
    e: "Choosing a heavyweight framework for a trivial task adds complexity for no benefit — a real anti-pattern.",
  },
  {
    c: "uAgent identity & addresses", cat: "application", t: "application", d: "medium",
    q: "Why are addresses (not function references) used between decentralized agents?",
    o: [
      "Functions are faster",
      "Agents may live in different processes/systems; addresses enable message routing without shared code",
      "Addresses are shorter",
      "To avoid using JSON",
    ],
    a: 1,
    e: "Decentralized agents don't share a process or codebase, so addressed message passing is how they communicate — direct function references wouldn't work across systems.",
  },
  {
    c: "Agent messaging & protocols", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Typed message models between agents mainly help by:",
    o: [
      "Making messages predictable and validatable",
      "Increasing temperature",
      "Reducing embedding size",
      "Removing the need for addresses",
    ],
    a: 0,
    e: "Typed models make messages predictable and validatable on both ends. Addresses are still needed for routing.",
  },
  {
    c: "Framework tradeoffs", cat: "architecture", t: "architecture", d: "hard",
    q: "Across frameworks, the concept that most consistently determines how you express control flow is:",
    o: [
      "The logo",
      "How the framework models orchestration and state",
      "The pricing page",
      "The default temperature",
    ],
    a: 1,
    e: "How a framework models orchestration and state is the axis that most shapes how you express control flow.",
  },
  {
    c: "Agent messaging & protocols", cat: "architecture", t: "architecture", d: "hard",
    q: "To make inter-agent communication maintainable as the system grows, you should:",
    o: [
      "Use ad-hoc free-text messages",
      "Define explicit protocols and typed messages so flows are documented and enforceable",
      "Share one global mutable object across all agents",
      "Increase temperature",
    ],
    a: 1,
    e: "Explicit protocols and typed messages document and enforce communication, scaling far better than ad-hoc text or shared mutable globals.",
  },
  {
    c: "Framework tradeoffs", cat: "application", t: "scenario", d: "easy",
    q: "You need a quick agent with tools and simple handoffs, minimal ceremony. A good fit is:",
    o: [
      "A lightweight agent SDK (e.g. OpenAI Agents SDK)",
      "A full decentralized network with addresses",
      "A spreadsheet",
      "A vector database alone",
    ],
    a: 0,
    e: "A lightweight agent SDK fits quick tool-using agents with handoffs. A decentralized network is overkill for that.",
  },
  {
    c: "uAgent identity & addresses", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Sending to a wrong/unknown uAgent address results in:",
    o: [
      "Guaranteed delivery",
      "The message not reaching the intended agent",
      "Automatic retraining",
      "A schema upgrade",
    ],
    a: 1,
    e: "An incorrect or unknown address means the message can't reach the intended recipient — an addressing failure.",
  },
  {
    c: "Framework tradeoffs", cat: "application", t: "application", d: "medium",
    q: "Which is the fairest way to compare frameworks for a project?",
    o: [
      "By popularity alone",
      "By how well their orchestration/state/tools/communication model fits your task's needs",
      "By which has the most GitHub stars",
      "By logo design",
    ],
    a: 1,
    e: "Fit-to-task along the core axes (orchestration, state, tools, communication) is the right basis for comparison, not popularity or aesthetics.",
  },
  {
    c: "Agent messaging & protocols", cat: "conceptual", t: "conceptual", d: "medium",
    q: "In uAgents, a message handler is responsible for:",
    o: [
      "Rendering a UI",
      "Receiving a specific message type and producing a response/action",
      "Chunking documents",
      "Setting embeddings",
    ],
    a: 1,
    e: "A handler receives a specific message model and defines the agent's response/action for it.",
  },
]);
