import { bank } from "./_builder";

// Day 8 — Agents × SwarmFolio / Deterministic Verification (25 questions)
export const day8 = bank("day-8", "Deterministic Verification", [
  {
    c: "Probabilistic vs deterministic", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Which pairing is correct?",
    o: [
      "LLM output = deterministic; feasibility check = probabilistic",
      "LLM output = probabilistic; feasibility check = deterministic",
      "Both are deterministic",
      "Both are probabilistic",
    ],
    a: 1,
    e: "LLM generation is probabilistic (variance across runs); a feasibility/math check is deterministic (exact, repeatable). Placing the deterministic check after the model is the core pattern.",
  },
  {
    c: "Probabilistic vs deterministic", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Why not trust a confident LLM answer as 'verified'?",
    o: [
      "Confidence tone doesn't establish correctness; only a deterministic check can verify a checkable claim",
      "LLMs can't produce confident answers",
      "Verification is impossible",
      "Confidence guarantees correctness",
    ],
    a: 0,
    e: "A confident tone is not evidence. For checkable claims, only a deterministic check (or real-world test) actually verifies correctness.",
  },
  {
    c: "Feasibility & infeasibility", cat: "conceptual", t: "conceptual", d: "easy",
    q: "'Infeasible' constraints mean:",
    o: [
      "The optimizer is slow",
      "No solution can satisfy all constraints simultaneously",
      "The constraints are unformatted",
      "There are too many constraints to list",
    ],
    a: 1,
    e: "Infeasibility means no solution satisfies every constraint at once — e.g. Tech ≥ 40% and Tech ≤ 25%.",
  },
  {
    c: "Feasibility & infeasibility", cat: "application", t: "scenario", d: "medium",
    q: "Constraints require Technology ≥ 40% and Technology ≤ 25%. A good system should:",
    o: [
      "Return a plausible-looking portfolio anyway",
      "Detect infeasibility and report it instead of fabricating a best-effort answer",
      "Silently drop one constraint",
      "Increase temperature and retry",
    ],
    a: 1,
    e: "The right behavior is to detect and report infeasibility, not to silently fabricate or drop constraints. This is the project's central principle.",
  },
  {
    c: "Feasibility & infeasibility", cat: "debugging", t: "failure-mode", d: "hard",
    q: "Which is the most dangerous failure for an impossible constraint set?",
    o: [
      "Reporting 'infeasible'",
      "Quantifying the conflict",
      "Silently returning a confident best-effort portfolio that violates a hard constraint",
      "Asking the user to relax a constraint",
    ],
    a: 2,
    e: "Silently returning a confident answer that violates a hard constraint is the dangerous outcome — it hides that the requirements can't be met. Reporting/quantifying/asking are all safe.",
  },
  {
    c: "Conflict detection", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Beyond saying 'infeasible', a good checker should:",
    o: [
      "Localize which constraints conflict and quantify the conflict",
      "Return only a boolean",
      "Increase k",
      "Change the embedding model",
    ],
    a: 0,
    e: "Localizing and quantifying the conflict (e.g. a 15pp gap) gives the agent concrete information to revise. A bare boolean is not actionable.",
  },
  {
    c: "Conflict detection", cat: "application", t: "scenario", d: "medium",
    q: "Tech min = 40%, Tech max = 25%. What is the conflict magnitude?",
    o: [
      "0 percentage points",
      "15 percentage points",
      "65 percentage points",
      "It cannot be quantified",
    ],
    a: 1,
    e: "The min exceeds the max by 40% − 25% = 15 percentage points — a quantifiable conflict the agent can act on.",
  },
  {
    c: "Feedback loop & revision", cat: "conceptual", t: "conceptual", d: "easy",
    q: "In the generate→check→revise loop, the deterministic checker's output is used to:",
    o: [
      "Decorate the UI",
      "Inform the agent's revision (relax/drop/adjust a constraint) and rerun",
      "Retrain the model",
      "Increase temperature",
    ],
    a: 1,
    e: "The checker's conflict explanation feeds back so the agent can revise constraints and rerun — closing the loop.",
  },
  {
    c: "Feedback loop & revision", cat: "application", t: "scenario", d: "hard",
    q: "After an INFEASIBLE result with a 15pp Tech conflict, the best agent revision is:",
    o: [
      "Re-guess random constraints ignoring the checker",
      "Use the conflict info to relax or drop one of the two conflicting Tech constraints, then rerun the check",
      "Return the infeasible set unchanged",
      "Ask a different LLM to average the numbers",
    ],
    a: 1,
    e: "Revision should be driven by the checker's specific feedback (the conflicting pair and gap), adjusting one constraint and re-verifying. Blind re-guessing wastes the feedback.",
  },
  {
    c: "Deterministic verification", cat: "conceptual", t: "conceptual", d: "medium",
    q: "The core philosophy 'build AI that is forced to answer to reality' is realized by:",
    o: [
      "Longer prompts",
      "Placing a deterministic verification step after probabilistic reasoning and revising on its result",
      "Higher temperature",
      "More agents",
    ],
    a: 1,
    e: "Forcing AI to 'answer to reality' means subjecting its claims to a deterministic check and revising based on the result — exactly the Day 8 pattern.",
  },
  {
    c: "Deterministic verification", cat: "architecture", t: "architecture", d: "hard",
    q: "Where must the LLM NOT be placed in this architecture?",
    o: [
      "Proposing constraints",
      "Revising constraints after feedback",
      "Inside the deterministic feasibility check itself",
      "Explaining the final result to the user",
    ],
    a: 2,
    e: "The feasibility check must remain deterministic; putting an LLM inside it reintroduces variance and defeats the verification. The LLM proposes, revises, and explains — but doesn't perform the exact check.",
  },
  {
    c: "Probabilistic vs deterministic", cat: "application", t: "scenario", d: "medium",
    q: "A step must compute whether weights sum to ≤ 1.0 exactly. Who should do it?",
    o: [
      "The LLM, from reasoning",
      "A deterministic function/tool",
      "A second LLM to double-check the first",
      "Nobody; assume it's fine",
    ],
    a: 1,
    e: "Exact arithmetic belongs to a deterministic function, not probabilistic generation or LLM cross-checks.",
  },
  {
    c: "Feasibility & infeasibility", cat: "conceptual", t: "conceptual", d: "medium",
    q: "A 'hard' constraint differs from a 'soft' constraint in that:",
    o: [
      "Hard constraints must be satisfied; soft constraints are preferences that can be traded off",
      "Hard constraints are optional",
      "Soft constraints must always be satisfied",
      "They are the same",
    ],
    a: 0,
    e: "Hard constraints must hold; soft constraints express preferences that can be relaxed/traded off. Distinguishing them is key to handling infeasibility.",
  },
  {
    c: "Conflict detection", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Reporting infeasibility without localizing the conflict is a weakness because:",
    o: [
      "It's too fast",
      "The agent/user has nothing specific to change, so revision is blind",
      "It uses too few tokens",
      "It requires a schema",
    ],
    a: 1,
    e: "Without knowing which constraints conflict and by how much, revision becomes guesswork. Localization/quantification makes revision targeted.",
  },
  {
    c: "Deterministic verification", cat: "conceptual", t: "conceptual", d: "easy",
    q: "The generate→verify→revise pattern is also known as:",
    o: [
      "An evaluator/optimizer (or generator/checker) loop",
      "A chunking pipeline",
      "An embedding index",
      "A prompt template",
    ],
    a: 0,
    e: "This is the evaluator/optimizer (generator/checker) loop: generate, check against a criterion, then revise.",
    ref: "Anthropic, Building effective agents",
  },
  {
    c: "Feedback loop & revision", cat: "conceptual", t: "conceptual", d: "medium",
    q: "What makes the feedback loop 'closed'?",
    o: [
      "The output is printed once",
      "The revised proposal is re-checked, and this repeats until feasible or a stop condition",
      "The LLM temperature is zero",
      "The corpus is embedded",
    ],
    a: 1,
    e: "A closed loop re-verifies each revision, iterating until it's feasible or a termination condition is hit.",
  },
  {
    c: "Probabilistic vs deterministic", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Deterministic computation means:",
    o: [
      "Same inputs always yield the same output",
      "Outputs vary randomly",
      "It requires an LLM",
      "It cannot be tested",
    ],
    a: 0,
    e: "Deterministic means identical inputs always produce identical outputs — exact and repeatable, unlike probabilistic generation.",
  },
  {
    c: "Feasibility & infeasibility", cat: "application", t: "scenario", d: "hard",
    q: "Constraints: Tech ≤ 25%, Finance ≤ 25%, Health ≤ 25%, and 'at least 80% across these three sectors'. Feasible?",
    o: [
      "Yes, easily",
      "No — the three caps sum to at most 75%, which cannot reach 80%",
      "Only with a bigger model",
      "Cannot be determined",
    ],
    a: 1,
    e: "Max across the three sectors is 25%×3 = 75% < 80%, so the set is infeasible — a deterministic check catches it exactly.",
  },
  {
    c: "Deterministic verification", cat: "architecture", t: "architecture", d: "hard",
    q: "How does deterministic verification connect AgentLab's own philosophy to the future system?",
    o: [
      "Both replace testing with vibes",
      "Both force a claim (a thesis, or an understanding) to answer to evidence via a test before it's accepted",
      "Neither uses evidence",
      "Only the future system uses evidence",
    ],
    a: 1,
    e: "AgentLab tests understanding with assessments; the future system tests theses with feasibility checks. Both reject 'looks plausible' in favor of claim→test→evidence→revision.",
  },
  {
    c: "Conflict detection", cat: "application", t: "scenario", d: "medium",
    q: "The checker should return, at minimum:",
    o: [
      "Only 'feasible' or 'infeasible'",
      "Feasibility, and if infeasible, which constraints conflict and by how much",
      "A random portfolio",
      "The embedding vectors",
    ],
    a: 1,
    e: "A useful checker returns feasibility plus, on failure, the conflicting constraints and the magnitude — enough for targeted revision.",
  },
  {
    c: "Feedback loop & revision", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Which behavior breaks the intended feedback loop?",
    o: [
      "Revising based on the checker's conflict report",
      "Ignoring the checker output and resubmitting the same infeasible constraints",
      "Re-running the check after revision",
      "Stopping when feasible",
    ],
    a: 1,
    e: "Resubmitting the same infeasible constraints ignores the feedback and prevents progress — it breaks the loop.",
  },
  {
    c: "Probabilistic vs deterministic", cat: "application", t: "scenario", d: "medium",
    q: "You want reproducible feasibility results in tests. The check should therefore be:",
    o: [
      "An LLM call at temperature 1",
      "A deterministic function with no LLM inside",
      "A multi-agent vote",
      "A random sampler",
    ],
    a: 1,
    e: "Reproducibility requires a deterministic function; LLM calls or votes introduce variance.",
  },
  {
    c: "Feasibility & infeasibility", cat: "conceptual", t: "conceptual", d: "easy",
    q: "'Relaxation' in constraint solving means:",
    o: [
      "Ignoring all constraints",
      "Loosening one or more (usually soft) constraints to make a problem feasible",
      "Adding more hard constraints",
      "Increasing temperature",
    ],
    a: 1,
    e: "Relaxation loosens constraints (typically soft ones) to recover feasibility. It's targeted, not wholesale ignoring.",
  },
  {
    c: "Deterministic verification", cat: "conceptual", t: "conceptual", d: "medium",
    q: "Why is a deterministic checker described as making AI 'prove it's right' rather than 'sound right'?",
    o: [
      "Because it rephrases the answer nicely",
      "Because it subjects the claim to an exact test that either passes or fails, independent of how persuasive the text is",
      "Because it uses a bigger model",
      "Because it hides the reasoning",
    ],
    a: 1,
    e: "An exact test passes or fails regardless of how convincing the prose is, forcing the claim to be proven rather than merely plausible.",
  },
  {
    c: "Conflict detection", cat: "architecture", t: "architecture", d: "hard",
    q: "To make conflict reports maximally useful to the revising agent, they should be:",
    o: [
      "Free-form prose only",
      "Structured (which constraints, the type of conflict, the quantified gap) so the agent can act programmatically",
      "A single boolean",
      "Hidden from the agent",
    ],
    a: 1,
    e: "Structured, quantified conflict reports let the agent act precisely and programmatically, far better than prose, a boolean, or hiding the information.",
  },
]);
