import { bank } from "./_builder";

// Day 9 — Comprehensive Mastery (40 questions across all topics).
// Concept names reuse earlier days so mistakes map back to the right concept.
export const day9 = bank("day-9", "Mastery & System Design", [
  // --- Agent fundamentals (5) ---
  {
    c: "LLM vs Agent", cat: "conceptual", t: "conceptual", d: "easy",
    q: "The single clearest sign a system is an agent (not just an LLM feature) is:",
    o: ["It uses a chat UI", "It loops, taking actions and observing results toward a goal", "It returns markdown", "It has a system prompt"],
    a: 1,
    e: "The defining trait is the act/observe loop toward a goal — not UI, formatting, or prompts.",
  },
  {
    c: "Agent loop", cat: "debugging", t: "debugging", d: "medium",
    q: "An agent loops forever on a task a single call could answer. Two fixes that address root causes:",
    o: [
      "Add a termination guard AND reconsider whether an agent is needed at all",
      "Raise temperature and add tools",
      "Increase k and re-embed",
      "Add memory and more agents",
    ],
    a: 0,
    e: "A missing termination guard plus over-use of an agent are the two root causes; bounding iterations and questioning the agent choice both apply.",
  },
  {
    c: "Tools & environment", cat: "architecture", t: "architecture", d: "hard",
    q: "An agent can execute shell commands. The most important safeguard is:",
    o: ["A bigger model", "Least-privilege environment scoping and confirmation for irreversible actions", "More few-shot examples", "Lower temperature"],
    a: 1,
    e: "Powerful, irreversible capabilities require bounding the environment (least privilege) and confirmation gates.",
  },
  {
    c: "When not to use agents", cat: "application", t: "scenario", d: "medium",
    q: "Which task should NOT be built as an autonomous agent?",
    o: ["Adaptive research across unpredictable sources", "Deterministically formatting a date string", "Multi-step tool use with branching", "A task whose steps depend on runtime observations"],
    a: 1,
    e: "Deterministic formatting is a plain function; the others genuinely benefit from adaptive/agentic control.",
  },
  {
    c: "Agent failure modes", cat: "debugging", t: "failure-mode", d: "medium",
    q: "An agent invents a tool `superSolve` you never defined. This is:",
    o: ["A chunking failure", "A hallucinated action; reject unknown tools at dispatch", "A termination failure", "A schema-sum error"],
    a: 1,
    e: "Inventing a nonexistent tool is a hallucinated action, fixed by rejecting unknown tool names at the dispatch boundary.",
  },
  // --- Tools (5) ---
  {
    c: "Function calling", cat: "conceptual", t: "conceptual", d: "easy",
    q: "Function calling means the model:",
    o: ["Runs your code", "Proposes a structured call your code executes", "Compiles functions", "Stores functions in memory"],
    a: 1,
    e: "The model proposes calls; your code validates and executes them.",
  },
  {
    c: "Argument validation", cat: "debugging", t: "debugging", d: "hard",
    q: "`setAllocation(sector, weight)` receives `weight: 1.7`. Schema says number. Best handling?",
    o: ["Accept it", "Silently clamp to 1.0", "Reject via business rule (weight ∈ [0,1]) and return a structured error observation", "Crash"],
    a: 2,
    e: "1.7 is schema-valid but business-invalid; reject with a structured error so the loop can correct.",
  },
  {
    c: "Tool selection", cat: "application", t: "scenario", d: "medium",
    q: "For an exact record lookup by ID, an agent keeps using semantic search. Best fix?",
    o: ["Increase top-k", "Clarify tool descriptions so exact lookups use the structured query tool", "Raise temperature", "Remove the ID field"],
    a: 1,
    e: "Using semantic search for exact lookups is a selection error fixed by clearer descriptions delineating exact vs semantic retrieval.",
  },
  {
    c: "Tool error handling", cat: "application", t: "scenario", d: "medium",
    q: "A flaky tool fails 15% of calls. Best policy?",
    o: ["Infinite retries", "Bounded retries with backoff, then graceful fallback", "Ignore errors", "Delete the tool"],
    a: 1,
    e: "Bounded retries with backoff handle transience; a fallback covers persistent failure.",
  },
  {
    c: "Tool schemas", cat: "conceptual", t: "conceptual", d: "easy",
    q: "A clear tool schema most directly reduces:",
    o: ["GPU cost", "Malformed/incorrect tool calls", "Embedding size", "Chunk count"],
    a: 1,
    e: "Clear schemas reduce malformed and incorrect calls by telling the model exactly how to call the tool.",
  },
  // --- RAG (5) ---
  {
    c: "Retrieval relevance", cat: "debugging", t: "debugging", d: "hard",
    q: "Three retrieved chunks are highly similar to the query but lack the answer, and the model hallucinates. Investigate FIRST:",
    o: ["Temperature", "Retrieval/relevance: is the needed info chunked, embedded, and retrievable?", "Output format", "System prompt tone"],
    a: 1,
    e: "Similar-but-irrelevant retrieval points at the retrieval layer, not generation settings.",
  },
  {
    c: "Why RAG exists", cat: "application", t: "scenario", d: "medium",
    q: "Best use of RAG for the future Research Agent:",
    o: ["Fine-tune nightly on all reports", "Retrieve only relevant report chunks at query time to ground answers", "Paste all reports into every prompt", "Rely on base-model knowledge"],
    a: 1,
    e: "RAG retrieves relevant chunks at query time, controlling cost/context while grounding answers in current data.",
  },
  {
    c: "Chunking", cat: "debugging", t: "debugging", d: "medium",
    q: "Answers miss facts spanning paragraph boundaries. Fix?",
    o: ["Tiny chunks, no overlap", "Add chunk overlap", "Remove chunking", "Raise temperature"],
    a: 1,
    e: "Overlap preserves ideas that span chunk boundaries.",
  },
  {
    c: "Embeddings", cat: "conceptual", t: "conceptual", d: "medium",
    q: "High cosine similarity to a query guarantees:",
    o: ["The chunk contains the answer", "The chunk is topically similar, not necessarily answer-bearing", "The chunk is newest", "The chunk is short"],
    a: 1,
    e: "Similarity = topical closeness, not presence of the specific fact.",
  },
  {
    c: "Grounding & hallucination", cat: "application", t: "scenario", d: "medium",
    q: "When retrieval finds nothing relevant, the grounded behavior is to:",
    o: ["Answer from priors confidently", "Say it can't find the information", "Lower the similarity threshold to force results", "Increase k until something returns"],
    a: 1,
    e: "With no relevant context, admitting it beats fabricating — the essence of grounding.",
  },
  // --- Structured outputs (5) ---
  {
    c: "Business-rule validation", cat: "conceptual", t: "conceptual", d: "medium",
    q: "`{maxSectorWeight: -5}` passing a 'number' schema shows:",
    o: ["The schema is broken", "Schema-valid ≠ business-valid", "JSON rejects negatives", "Models can't emit numbers"],
    a: 1,
    e: "A negative weight is a valid number but semantically illegal — schema-valid isn't business-valid.",
  },
  {
    c: "Business-rule validation", cat: "debugging", t: "debugging", d: "hard",
    q: "Tech min 0.40 and Tech max 0.25 each pass individual validation. The validator must ALSO:",
    o: ["Check indentation", "Detect the cross-constraint contradiction (min>max) and quantify it", "Sort fields", "Re-embed"],
    a: 1,
    e: "Cross-constraint consistency catches min>max and quantifies the 15pp gap.",
  },
  {
    c: "Schema validation", cat: "application", t: "application", d: "easy",
    q: "Restricting `type` to a fixed set of strings uses:",
    o: ["A number type", "An enum", "A nullable field", "A regex on numbers"],
    a: 1,
    e: "An enum restricts a field to a fixed allowed set.",
  },
  {
    c: "Structured output", cat: "architecture", t: "architecture", d: "hard",
    q: "Best place for the validation layer:",
    o: ["Inside the deterministic engine", "Between the LLM and the engine, so the engine gets trustworthy inputs", "In the UI only", "Nowhere; trust the model"],
    a: 1,
    e: "A boundary validator keeps engine inputs clean and localizes LLM-error handling.",
  },
  {
    c: "Malformed output handling", cat: "application", t: "scenario", d: "medium",
    q: "Model JSON is occasionally unparseable. Robust handling:",
    o: ["Crash", "Catch and re-prompt/repair within bounded attempts", "Return empty object silently", "Assume it never happens"],
    a: 1,
    e: "Catch and recover with bounded attempts; don't crash or silently swallow.",
  },
  // --- State / orchestration (4) ---
  {
    c: "State", cat: "conceptual", t: "conceptual", d: "medium",
    q: "State vs memory:",
    o: ["Identical", "State is within-run working data; memory persists beyond the immediate context", "Memory is faster", "State only exists with multiple agents"],
    a: 1,
    e: "State is within-run; memory persists across contexts/runs.",
  },
  {
    c: "Orchestration", cat: "application", t: "scenario", d: "medium",
    q: "Two independent subtasks with no data dependency should run:",
    o: ["Sequentially", "In parallel", "Conditionally on each other", "Never together"],
    a: 1,
    e: "Independent subtasks parallelize to cut latency.",
  },
  {
    c: "Retries & termination", cat: "debugging", t: "debugging", d: "hard",
    q: "A workflow hangs because a success condition is never met, so it retries endlessly. Fix:",
    o: ["Remove logging", "Bound retries and define a graceful give-up/termination path", "Increase temperature", "Add steps"],
    a: 1,
    e: "Bound retries and define what happens when the condition can't be met.",
  },
  {
    c: "State", cat: "architecture", t: "architecture", d: "medium",
    q: "To minimize state bugs across steps:",
    o: ["One global mutable variable", "Pass an explicit state object; steps read only what earlier steps wrote", "No state", "Store state in prompt text only"],
    a: 1,
    e: "Explicit, forward-passed state with clear read/write boundaries reduces corruption.",
  },
  // --- Multi-agent (5) ---
  {
    c: "Conflict & aggregation", cat: "application", t: "scenario", d: "hard",
    q: "A committee blends a bullish and bearish view into '5/10' with no explanation. Problem?",
    o: ["Nothing", "It silently averaged away a material conflict the decision-maker needs", "Too few agents", "Wrong embeddings"],
    a: 1,
    e: "Silent averaging hides the disagreement that matters most; surface it instead.",
  },
  {
    c: "When not to use multiple agents", cat: "conceptual", t: "conceptual", d: "medium",
    q: "You should NOT use multiple agents when:",
    o: ["A single agent/workflow suffices", "Roles genuinely differ", "Independent critique adds real value", "Subtasks truly parallelize with benefit"],
    a: 0,
    e: "If one agent/workflow suffices, multi-agent only adds cost and failure surface.",
  },
  {
    c: "Multi-agent cost", cat: "application", t: "scenario", d: "medium",
    q: "5 agents give the same quality as 1 but cost 5x and are slower. Do:",
    o: ["Keep 5", "Use 1 — the overhead isn't justified", "Add a 6th", "Raise temperature"],
    a: 1,
    e: "Unjustified multi-agent overhead should be removed.",
  },
  {
    c: "Multi-agent value", cat: "architecture", t: "architecture", d: "hard",
    q: "Separating Research, Macro, and Risk into agents is justified because:",
    o: ["It uses more compute", "They have genuinely different objectives and independent perspectives improve the decision", "Single agents can't call tools", "It avoids structured output"],
    a: 1,
    e: "Distinct objectives + valuable independent perspectives justify specialization.",
  },
  {
    c: "Coordination", cat: "debugging", t: "failure-mode", d: "medium",
    q: "Two agents redundantly do the same work. This is a failure of:",
    o: ["Coordination", "Embeddings", "Schema validation", "Termination"],
    a: 0,
    e: "Redundant work means roles/tasks weren't partitioned — a coordination failure.",
  },
  // --- Frameworks / uAgents (3) ---
  {
    c: "Framework tradeoffs", cat: "conceptual", t: "conceptual", d: "medium",
    q: "The most efficient way to compare frameworks:",
    o: ["By GitHub stars", "By how their orchestration/state/tools/communication fit your task", "By logo", "By release date"],
    a: 1,
    e: "Compare on fit along the core axes, not popularity/aesthetics.",
  },
  {
    c: "uAgent identity & addresses", cat: "conceptual", t: "conceptual", d: "easy",
    q: "One uAgent reaches another by:",
    o: ["Importing its function", "Messaging its address", "Editing its weights", "Sharing a global variable"],
    a: 1,
    e: "uAgents communicate via addressed message passing.",
  },
  {
    c: "Agent messaging & protocols", cat: "debugging", t: "debugging", d: "hard",
    q: "Addresses are correct but B ignores A's messages. Likely cause:",
    o: ["Low temperature", "B has no handler for A's message model (model mismatch)", "Wrong embeddings", "Too many tools"],
    a: 1,
    e: "With correct addressing, a missing/mismatched message handler explains silent drops.",
  },
  // --- Deterministic verification / integration (5) ---
  {
    c: "Feasibility & infeasibility", cat: "application", t: "scenario", d: "medium",
    q: "Tech ≥ 40% and Tech ≤ 25% requested. Correct system behavior:",
    o: ["Return a plausible portfolio anyway", "Detect and report infeasibility rather than fabricate", "Drop one constraint silently", "Retry at higher temperature"],
    a: 1,
    e: "Detect and report infeasibility; never silently fabricate or drop constraints.",
  },
  {
    c: "Deterministic verification", cat: "architecture", t: "architecture", d: "hard",
    q: "In the AI Investment Committee, the LLM must NOT be placed:",
    o: ["Proposing constraints", "Inside the deterministic feasibility check", "Revising after feedback", "Explaining results"],
    a: 1,
    e: "The check must stay deterministic; an LLM inside it reintroduces variance and defeats verification.",
  },
  {
    c: "Conflict detection", cat: "application", t: "scenario", d: "medium",
    q: "Beyond 'infeasible', the checker should return:",
    o: ["A random portfolio", "Which constraints conflict and the quantified gap", "Only a boolean", "The embeddings"],
    a: 1,
    e: "Localized, quantified conflicts enable targeted revision.",
  },
  {
    c: "Feedback loop & revision", cat: "application", t: "scenario", d: "hard",
    q: "After INFEASIBLE with a 15pp Tech conflict, the best revision:",
    o: ["Re-guess randomly", "Use the feedback to relax/drop one conflicting constraint and re-check", "Resubmit unchanged", "Average the numbers with another LLM"],
    a: 1,
    e: "Revision should be driven by the checker's specific feedback, then re-verified.",
  },
  {
    c: "Deterministic verification", cat: "architecture", t: "architecture", d: "hard",
    q: "The end-to-end future loop is best summarized as:",
    o: [
      "AI reasoning → 'looks good' → done",
      "AI reasoning → structured constraints → deterministic feasibility → feedback → AI revision → re-check",
      "Retrieve → embed → chunk → answer",
      "Prompt → fine-tune → deploy",
    ],
    a: 1,
    e: "The system routes probabilistic reasoning through structured constraints and a deterministic check, then revises on feedback — claim→test→evidence→revision.",
  },
  // --- Extra integration / judgment (3) ---
  {
    c: "When not to use agents", cat: "architecture", t: "architecture", d: "medium",
    q: "Designing the committee, which part should be a plain deterministic function rather than an agent?",
    o: [
      "Interpreting a qualitative thesis",
      "Checking whether the proposed constraints are feasible",
      "Deciding which research sources to read",
      "Explaining a decision in prose",
    ],
    a: 1,
    e: "Feasibility checking is exact and repeatable — a deterministic function. Interpretation, source selection, and explanation are where the probabilistic model adds value.",
  },
  {
    c: "Tool error handling", cat: "debugging", t: "debugging", d: "medium",
    q: "In the committee, the market-data tool times out mid-run. The most resilient behavior is to:",
    o: [
      "Crash the whole committee",
      "Return the timeout as an observation so the agent can retry or proceed with a noted gap",
      "Silently use last week's cached data as if current",
      "Skip risk analysis entirely without noting it",
    ],
    a: 1,
    e: "Surfacing the timeout as an observation lets the system adapt and stay honest about gaps. Crashing, silent stale data, and unlogged skips are all worse.",
  },
  {
    c: "Grounding & hallucination", cat: "architecture", t: "architecture", d: "hard",
    q: "To keep the Research Agent's claims trustworthy, which two design choices matter most?",
    o: [
      "High temperature and more agents",
      "Ground answers in retrieved sources with citations, and route checkable claims through deterministic verification",
      "Longer prompts and bigger context only",
      "Hiding sources to reduce clutter",
    ],
    a: 1,
    e: "Trustworthy claims come from grounding + citations (so answers trace to sources) and deterministic verification of checkable claims — the project's core 'answer to reality' principle.",
  },
]);
